using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OrcaFacil.Domain.Entities;

namespace OrcaFacil.Persistence.Configurations;

public sealed class BusinessUnitConfiguration : IEntityTypeConfiguration<BusinessUnit> { public void Configure(EntityTypeBuilder<BusinessUnit> b) { b.ToTable("business_units"); b.ConfigureBase(); b.Property(x=>x.Name).HasMaxLength(160).IsRequired(); b.Property(x=>x.State).HasMaxLength(2); b.HasIndex(x=>new{x.AccountId,x.Name}); b.HasIndex(x=>x.AccountId).HasFilter("is_main AND is_active AND NOT is_deleted").IsUnique(); } }
public sealed class BusinessUnitMemberConfiguration : IEntityTypeConfiguration<BusinessUnitMember> { public void Configure(EntityTypeBuilder<BusinessUnitMember> b) { b.ToTable("business_unit_members"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.BusinessUnitId,x.UserId}).IsUnique(); } }
public sealed class TeamConfiguration : IEntityTypeConfiguration<Team> { public void Configure(EntityTypeBuilder<Team> b) { b.ToTable("teams"); b.ConfigureBase(); b.Property(x=>x.Name).HasMaxLength(160).IsRequired(); b.Property(x=>x.Type).HasConversion<string>().HasMaxLength(24); b.HasIndex(x=>new{x.AccountId,x.Name}).IsUnique(); } }
public sealed class TeamMemberConfiguration : IEntityTypeConfiguration<TeamMember> { public void Configure(EntityTypeBuilder<TeamMember> b) { b.ToTable("team_members"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.TeamId,x.UserId}).IsUnique(); } }
public sealed class RoleProfileConfiguration : IEntityTypeConfiguration<RoleProfile> { public void Configure(EntityTypeBuilder<RoleProfile> b) { b.ToTable("role_profiles"); b.ConfigureBase(); b.Property(x=>x.Name).HasMaxLength(100).IsRequired(); b.HasIndex(x=>new{x.AccountId,x.Name}).IsUnique(); } }
public sealed class RoleProfilePermissionConfiguration : IEntityTypeConfiguration<RoleProfilePermission> { public void Configure(EntityTypeBuilder<RoleProfilePermission> b) { b.ToTable("role_profile_permissions"); b.ConfigureBase(); b.Property(x=>x.PermissionCode).HasMaxLength(120).IsRequired(); b.HasIndex(x=>new{x.AccountId,x.RoleProfileId,x.PermissionCode}).IsUnique(); } }
public sealed class DiscountPolicyConfiguration : IEntityTypeConfiguration<DiscountPolicy> { public void Configure(EntityTypeBuilder<DiscountPolicy> b) { b.ToTable("discount_policies"); b.ConfigureBase(); b.Property(x=>x.Name).HasMaxLength(160).IsRequired(); b.HasIndex(x=>new{x.AccountId,x.BusinessUnitId,x.IsActive}); } }
public sealed class ApprovalRequestConfiguration : IEntityTypeConfiguration<ApprovalRequest> { public void Configure(EntityTypeBuilder<ApprovalRequest> b) { b.ToTable("approval_requests"); b.ConfigureBase(); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(24); b.Property(x=>x.Reason).HasMaxLength(1000); b.HasIndex(x=>new{x.AccountId,x.Status,x.ApproverUserId}); b.HasIndex(x=>new{x.AccountId,x.DocumentId}).HasFilter("status = 'Pending' AND NOT is_deleted").IsUnique(); } }
public sealed class ApprovalRequestEventConfiguration : IEntityTypeConfiguration<ApprovalRequestEvent> { public void Configure(EntityTypeBuilder<ApprovalRequestEvent> b) { b.ToTable("approval_request_events"); b.ConfigureBase(); b.Property(x=>x.Type).HasConversion<string>().HasMaxLength(24); b.Property(x=>x.Comment).HasMaxLength(2000); b.HasIndex(x=>new{x.AccountId,x.ApprovalRequestId,x.CreatedAt}); } }
public sealed class WhiteLabelSettingConfiguration : IEntityTypeConfiguration<WhiteLabelSetting> { public void Configure(EntityTypeBuilder<WhiteLabelSetting> b) { b.ToTable("white_label_settings"); b.ConfigureBase(); b.HasIndex(x=>x.AccountId).IsUnique(); } }
public sealed class UnitBrandingProfileConfiguration : IEntityTypeConfiguration<UnitBrandingProfile> { public void Configure(EntityTypeBuilder<UnitBrandingProfile> b) { b.ToTable("unit_branding_profiles"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.BusinessUnitId}).IsUnique(); } }
public sealed class DocumentVisibilityRuleConfiguration : IEntityTypeConfiguration<DocumentVisibilityRule> { public void Configure(EntityTypeBuilder<DocumentVisibilityRule> b) { b.ToTable("document_visibility_rules"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.BusinessUnitId,x.TeamId,x.UserId}); } }
