using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OrcaFacil.Domain.Entities;

namespace OrcaFacil.Persistence.Configurations;

public sealed class BackgroundJobConfiguration : IEntityTypeConfiguration<BackgroundJob> { public void Configure(EntityTypeBuilder<BackgroundJob> b) { b.ToTable("background_jobs", "orcafacil"); b.ConfigureBase(); b.Property(x=>x.Name).HasMaxLength(160); b.Property(x=>x.Schedule).HasMaxLength(80); b.HasIndex(x=>x.Name).IsUnique(); } }
public sealed class JobExecutionConfiguration : IEntityTypeConfiguration<JobExecution> { public void Configure(EntityTypeBuilder<JobExecution> b) { b.ToTable("job_executions", "orcafacil"); b.ConfigureBase(); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(24); b.Property(x=>x.ErrorSummary).HasMaxLength(500); b.HasIndex(x=>x.ExecutionId).IsUnique(); b.HasIndex(x=>new{x.JobName,x.StartedAt}); } }
public sealed class JobLockConfiguration : IEntityTypeConfiguration<JobLock> { public void Configure(EntityTypeBuilder<JobLock> b) { b.ToTable("job_locks", "orcafacil"); b.ConfigureBase(); b.Property(x=>x.Name).HasMaxLength(160); b.Property(x=>x.LockedBy).HasMaxLength(160); b.HasIndex(x=>x.Name).IsUnique(); } }
public sealed class ProcessingOutboxItemConfiguration : IEntityTypeConfiguration<ProcessingOutboxItem> { public void Configure(EntityTypeBuilder<ProcessingOutboxItem> b) { b.ToTable("processing_outbox", "orcafacil"); b.ConfigureBase(); b.Property(x=>x.Type).HasMaxLength(80); b.Property(x=>x.IdempotencyKey).HasMaxLength(200); b.Property(x=>x.PayloadJson).HasColumnType("jsonb"); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(24); b.Property(x=>x.LastError).HasMaxLength(500); b.HasIndex(x=>new{x.AccountId,x.IdempotencyKey}).IsUnique(); b.HasIndex(x=>new{x.Status,x.NextAttemptAt,x.Priority}); } }
public sealed class SystemMetricConfiguration : IEntityTypeConfiguration<SystemMetric> { public void Configure(EntityTypeBuilder<SystemMetric> b) { b.ToTable("system_metrics","orcafacil"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.Name,x.PeriodStart}); } }
public sealed class SlowQueryLogConfiguration : IEntityTypeConfiguration<SlowQueryLog> { public void Configure(EntityTypeBuilder<SlowQueryLog> b) { b.ToTable("slow_query_logs","orcafacil"); b.ConfigureBase(); b.Property(x=>x.Summary).HasMaxLength(500); b.HasIndex(x=>new{x.AccountId,x.CreatedAt}); b.HasIndex(x=>new{x.Route,x.CreatedAt}); } }
public sealed class TenantUsageMetricConfiguration : IEntityTypeConfiguration<TenantUsageMetric> { public void Configure(EntityTypeBuilder<TenantUsageMetric> b) { b.ToTable("tenant_usage_metrics","orcafacil"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.Resource,x.PeriodStart}).IsUnique(); } }
public sealed class CacheInvalidationEventConfiguration : IEntityTypeConfiguration<CacheInvalidationEvent> { public void Configure(EntityTypeBuilder<CacheInvalidationEvent> b) { b.ToTable("cache_invalidation_events","orcafacil"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.CreatedAt}); } }
public sealed class QuotaEventConfiguration : IEntityTypeConfiguration<QuotaEvent> { public void Configure(EntityTypeBuilder<QuotaEvent> b) { b.ToTable("quota_events","orcafacil"); b.ConfigureBase(); b.HasIndex(x=>new{x.AccountId,x.CreatedAt}); } }
public sealed class RateLimitEventConfiguration : IEntityTypeConfiguration<RateLimitEvent> { public void Configure(EntityTypeBuilder<RateLimitEvent> b) { b.ToTable("rate_limit_events","orcafacil"); b.ConfigureBase(); b.HasIndex(x=>new{x.Policy,x.CreatedAt}); } }
public sealed class WorkerHeartbeatConfiguration : IEntityTypeConfiguration<WorkerHeartbeat> { public void Configure(EntityTypeBuilder<WorkerHeartbeat> b) { b.ToTable("worker_heartbeats","orcafacil"); b.ConfigureBase(); b.HasIndex(x=>x.InstanceId).IsUnique(); } }
