<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrcaFacil.Application\OrcaFacil.Application.csproj" />
    <ProjectReference Include="..\OrcaFacil.Infrastructure\OrcaFacil.Infrastructure.csproj" />
    <ProjectReference Include="..\OrcaFacil.Persistence\OrcaFacil.Persistence.csproj" />
    <ProjectReference Include="..\OrcaFacil.Shared\OrcaFacil.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0-preview.6.25358.103" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
    <Content Update="appsettings.Local.example.json">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
