using System.Text.Json; using Microsoft.AspNetCore.DataProtection; using Microsoft.EntityFrameworkCore; using OrcaFacil.Domain.Entities; using OrcaFacil.Persistence; using OrcaFacil.Web.Security;
namespace OrcaFacil.Web.Email;
public sealed class EmailOutboxWorker(IServiceScopeFactory scopes,IDataProtectionProvider protection,ILogger<EmailOutboxWorker> logger):BackgroundService
{
 readonly string _instance=$"{Environment.MachineName}:{Guid.NewGuid():N}";
 protected override async Task ExecuteAsync(CancellationToken stoppingToken){using var timer=new PeriodicTimer(TimeSpan.FromSeconds(5));do{try{await ProcessAsync(stoppingToken);}catch(OperationCanceledException) when(stoppingToken.IsCancellationRequested){break;}catch(Exception ex){logger.LogError(ex,"EMAIL_OUTBOX_CYCLE_FAILED");}}while(await timer.WaitForNextTickAsync(stoppingToken));}
 async Task ProcessAsync(CancellationToken ct){using var scope=scopes.CreateScope();var db=scope.ServiceProvider.GetRequiredService<OrcaFacilDbContext>();var sender=scope.ServiceProvider.GetRequiredService<IEmailSender>();var now=DateTime.UtcNow;await db.EmailOutboxMessages.Where(x=>x.Status==EmailOutboxStatus.Processing&&x.ProcessingStartedAt<now.AddMinutes(-10)).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.Status,EmailOutboxStatus.Pending).SetProperty(x=>x.ProcessingInstanceId,(string?)null),ct);var ids=await db.EmailOutboxMessages.Where(x=>(x.Status==EmailOutboxStatus.Pending||x.Status==EmailOutboxStatus.Failed)&&x.NextAttemptAt<=now&&x.Attempts<5).OrderBy(x=>x.Priority).ThenBy(x=>x.CreatedAt).Select(x=>x.Id).Take(5).ToListAsync(ct);foreach(var id in ids){var claimed=await db.EmailOutboxMessages.Where(x=>x.Id==id&&(x.Status==EmailOutboxStatus.Pending||x.Status==EmailOutboxStatus.Failed)).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.Status,EmailOutboxStatus.Processing).SetProperty(x=>x.ProcessingStartedAt,now).SetProperty(x=>x.ProcessingInstanceId,_instance).SetProperty(x=>x.Attempts,x=>x.Attempts+1),ct);if(claimed==0)continue;var item=await db.EmailOutboxMessages.SingleAsync(x=>x.Id==id,ct);try{var recipient=protection.CreateProtector("OrcaFacil.EmailOutbox.Recipient.v1").Unprotect(item.ProtectedRecipient);var json=protection.CreateProtector("OrcaFacil.EmailOutbox.Payload.v1").Unprotect(item.ProtectedPayload!);var payload=JsonSerializer.Deserialize<OutboxPayload>(json)!;if(payload.ExpiresAt<=DateTime.UtcNow){item.Status=EmailOutboxStatus.DeadLetter;item.DeadLetteredAt=DateTime.UtcNow;item.LastErrorCode="CONTENT_EXPIRED";}else{var result=await sender.SendAsync(new EmailMessage(new EmailAddress(recipient),payload.Subject,payload.Text,payload.Html),ct);if(result.Succeeded){item.Status=EmailOutboxStatus.Sent;item.SentAt=DateTime.UtcNow;item.ProtectedPayload=null;item.ProtectedRecipient=string.Empty;logger.LogInformation("PASSWORD_RESET_EMAIL_SENT CorrelationId {CorrelationId} Recipient {Recipient}",item.CorrelationId,item.RecipientMasked);}else Fail(item,result.Code);}}catch(Exception ex){logger.LogWarning("EMAIL_OUTBOX_ITEM_FAILED Id {Id} Type {Type}",id,ex.GetType().Name);Fail(item,"PROCESSING_FAILED");}item.ProcessingInstanceId=null;item.ProcessingStartedAt=null;await db.SaveChangesAsync(ct);}}
 static void Fail(EmailOutboxMessage item,string? code){item.LastErrorCode=code;if(item.Attempts>=5){item.Status=EmailOutboxStatus.DeadLetter;item.DeadLetteredAt=DateTime.UtcNow;}else{item.Status=EmailOutboxStatus.Failed;item.NextAttemptAt=DateTime.UtcNow.AddSeconds(Math.Pow(2,item.Attempts)*15);}}
}
