using Microsoft.Extensions.Options;
namespace OrcaFacil.Web.Email;
public sealed class EmailOptions { public string Provider {get;set;}=""; public string Host {get;set;}=""; public int Port {get;set;}=587; public string SocketOptions {get;set;}="StartTls"; public string Username {get;set;}=""; public string Password {get;set;}=""; public string FromAddress {get;set;}=""; public string FromName {get;set;}="OrçaFácil"; public string ReplyTo {get;set;}=""; public int TimeoutSeconds {get;set;}=20; }
public sealed class EmailOptionsValidator : IValidateOptions<EmailOptions> { public ValidateOptionsResult Validate(string? n, EmailOptions o) { var e=new List<string>(); if(string.IsNullOrWhiteSpace(o.Host))e.Add("EMAIL_HOST_REQUIRED"); if(o.Port is <1 or >65535)e.Add("EMAIL_PORT_INVALID"); if(!o.SocketOptions.Equals("StartTls",StringComparison.OrdinalIgnoreCase))e.Add("EMAIL_TLS_REQUIRED"); if(string.IsNullOrWhiteSpace(o.Username))e.Add("EMAIL_USERNAME_REQUIRED"); if(string.IsNullOrWhiteSpace(o.Password)||o.Password.Contains("INFORME",StringComparison.OrdinalIgnoreCase))e.Add("EMAIL_PASSWORD_REQUIRED"); if(!System.Net.Mail.MailAddress.TryCreate(o.FromAddress,out _))e.Add("EMAIL_FROM_INVALID"); if(!string.Equals(o.FromAddress,o.Username,StringComparison.OrdinalIgnoreCase))e.Add("EMAIL_FROM_MISMATCH"); if(o.TimeoutSeconds is <1 or >120)e.Add("EMAIL_TIMEOUT_INVALID"); return e.Count==0?ValidateOptionsResult.Success:ValidateOptionsResult.Fail(e); } }
public sealed class PasswordResetOptions { public int TokenLifetimeMinutes{get;set;}=30; public int MinimumRequestIntervalSeconds{get;set;}=60; public int MaximumRequestsPerHour{get;set;}=3; }
public sealed class PasswordResetOptionsValidator:IValidateOptions<PasswordResetOptions>{public ValidateOptionsResult Validate(string? n,PasswordResetOptions o)=>o.TokenLifetimeMinutes is >=5 and <=120&&o.MinimumRequestIntervalSeconds is >=10 and <=3600&&o.MaximumRequestsPerHour is >=1 and <=20?ValidateOptionsResult.Success:ValidateOptionsResult.Fail("PASSWORD_RESET_LIMITS_INVALID");}
public sealed class ApplicationUrlOptions { public string PublicBaseUrl{get;set;}=""; }
public sealed class SecuritySecretOptions { public string PasswordResetPepper{get;set;}=""; public string SecurityEventPepper{get;set;}=""; }
public sealed class SecuritySecretOptionsValidator:IValidateOptions<SecuritySecretOptions>{public ValidateOptionsResult Validate(string? n,SecuritySecretOptions o){static bool Bad(string x)=>string.IsNullOrWhiteSpace(x)||x.Length<32||x.Contains("INFORME",StringComparison.OrdinalIgnoreCase)||x.Contains("GERE_",StringComparison.OrdinalIgnoreCase); return !Bad(o.PasswordResetPepper)&&!Bad(o.SecurityEventPepper)&&o.PasswordResetPepper!=o.SecurityEventPepper?ValidateOptionsResult.Success:ValidateOptionsResult.Fail("SECURITY_SECRETS_INVALID");}}
