using MailKit.Net.Smtp; using MailKit.Security; using Microsoft.Extensions.Options; using MimeKit;
namespace OrcaFacil.Web.Email;
public sealed record EmailAddress(string Address,string? Name=null); public sealed record EmailMessage(EmailAddress To,string Subject,string TextBody,string HtmlBody,string? ReplyTo=null); public enum EmailFailureCategory{Configuration,Authentication,Tls,Timeout,Quota,RecipientRejected,Transient,Unexpected} public sealed record EmailSendResult(bool Succeeded,string? MessageId=null,EmailFailureCategory? Failure=null,string? Code=null);
public interface IEmailSender{Task<EmailSendResult> SendAsync(EmailMessage message,CancellationToken ct);}
public sealed class GmailSmtpEmailSender(IOptions<EmailOptions> settings,ILogger<GmailSmtpEmailSender> logger):IEmailSender
{
 public async Task<EmailSendResult> SendAsync(EmailMessage message,CancellationToken ct){var o=settings.Value; using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct); timeout.CancelAfter(TimeSpan.FromSeconds(o.TimeoutSeconds)); try{var mime=new MimeMessage();mime.From.Add(new MailboxAddress(o.FromName,o.FromAddress));mime.To.Add(new MailboxAddress(message.To.Name??string.Empty,message.To.Address));mime.Subject=message.Subject;mime.ReplyTo.Add(MailboxAddress.Parse(message.ReplyTo??o.ReplyTo));mime.Body=new BodyBuilder{TextBody=message.TextBody,HtmlBody=message.HtmlBody}.ToMessageBody();using var smtp=new SmtpClient();await smtp.ConnectAsync(o.Host,o.Port,SecureSocketOptions.StartTls,timeout.Token);await smtp.AuthenticateAsync(o.Username,o.Password,timeout.Token);await smtp.SendAsync(mime,timeout.Token);await smtp.DisconnectAsync(true,timeout.Token);logger.LogInformation("EMAIL_SENT Recipient {Recipient} MessageId {MessageId}",Mask(message.To.Address),mime.MessageId);return new(true,mime.MessageId);}catch(OperationCanceledException) when(!ct.IsCancellationRequested){return new(false,Failure:EmailFailureCategory.Timeout,Code:"SMTP_TIMEOUT");}catch(AuthenticationException){return new(false,Failure:EmailFailureCategory.Authentication,Code:"SMTP_AUTHENTICATION");}catch(SslHandshakeException){return new(false,Failure:EmailFailureCategory.Tls,Code:"SMTP_TLS");}catch(Exception ex){logger.LogWarning("EMAIL_SEND_FAILED Type {Type}",ex.GetType().Name);return new(false,Failure:EmailFailureCategory.Transient,Code:"SMTP_TRANSIENT");}}
 static string Mask(string value){var at=value.IndexOf('@');return at<=1?"***":$"{value[0]}***{value[(at-1)..]}";}
}
