using OrcaFacil.Domain.Common;

namespace OrcaFacil.Domain.Entities;

public enum FinancialCategoryType { Revenue, Expense, DirectCost, IndirectCost, Tax, Fee, Investment, Transfer, Adjustment }
public enum CashMovementType { Entry, Exit, Transfer, PositiveAdjustment, NegativeAdjustment, Reversal }
public enum PayableStatus { Draft, Open, PartiallyPaid, Paid, Overdue, Canceled, Reversed }
public enum PayablePaymentStatus { Confirmed, Reversed }
public enum RecurrenceFrequency { Monthly, Bimonthly, Quarterly, Semiannual, Annual, Custom }
public enum FiscalRequestStatus { Pending, InReview, Issued, Rejected, Canceled, NotRequired }

public sealed class FinancialCategory : Entity { public Guid AccountId { get; set; } public Guid? ParentCategoryId { get; set; } public string Name { get; set; } = ""; public FinancialCategoryType Type { get; set; } public string Code { get; set; } = ""; public string? Description { get; set; } public bool IsSystem { get; set; } public bool IsActive { get; set; } = true; }
public sealed class CostCenter : Entity { public Guid AccountId { get; set; } public Guid? BusinessUnitId { get; set; } public string Name { get; set; } = ""; public string Code { get; set; } = ""; public string? Description { get; set; } public Guid? ResponsibleUserId { get; set; } public bool IsActive { get; set; } = true; }
public sealed class BankAccount : Entity { public Guid AccountId { get; set; } public string Name { get; set; } = ""; public string BankName { get; set; } = ""; public string? Agency { get; set; } public string AccountNumberMasked { get; set; } = ""; public string? PixKeyMasked { get; set; } public decimal OpeningBalance { get; set; } public decimal CurrentBalance { get; set; } public bool IsDefault { get; set; } public bool IsActive { get; set; } = true; }
public sealed class CashMovement : Entity { public Guid AccountId { get; set; } public Guid BankAccountId { get; set; } public CashMovementType Type { get; set; } public decimal Amount { get; set; } public DateTime MovementDate { get; set; } public string Description { get; set; } = ""; public string? Reason { get; set; } public Guid? ReversesMovementId { get; set; } public string? IdempotencyKey { get; set; } public Guid CreatedByUserId { get; set; } }
public sealed class Payable : Entity { public Guid AccountId { get; set; } public Guid? SupplierId { get; set; } public Guid? ClientId { get; set; } public Guid? PurchaseOrderId { get; set; } public Guid? WorkOrderId { get; set; } public Guid? ContractId { get; set; } public Guid? CategoryId { get; set; } public Guid? CostCenterId { get; set; } public string Description { get; set; } = ""; public PayableStatus Status { get; set; } = PayableStatus.Open; public DateTime IssueDate { get; set; } public DateTime DueDate { get; set; } public DateTime? CompetenceDate { get; set; } public decimal TotalAmount { get; set; } public decimal PaidAmount { get; set; } public decimal BalanceAmount { get; set; } public string? PaymentMethod { get; set; } public string? Notes { get; set; } }
public sealed class PayablePayment : Entity { public Guid AccountId { get; set; } public Guid PayableId { get; set; } public Guid BankAccountId { get; set; } public decimal Amount { get; set; } public DateTime PaymentDate { get; set; } public string PaymentMethod { get; set; } = ""; public string? Reference { get; set; } public string? Notes { get; set; } public PayablePaymentStatus Status { get; set; } = PayablePaymentStatus.Confirmed; public Guid CreatedByUserId { get; set; } public Guid? CashMovementId { get; set; } public string IdempotencyKey { get; set; } = ""; }
public sealed class PayableRecurrence : Entity { public Guid AccountId { get; set; } public Guid? SupplierId { get; set; } public Guid? CategoryId { get; set; } public Guid? CostCenterId { get; set; } public string Description { get; set; } = ""; public decimal Amount { get; set; } public RecurrenceFrequency Frequency { get; set; } public DateTime StartDate { get; set; } public DateTime? EndDate { get; set; } public DateTime NextDueDate { get; set; } public bool IsActive { get; set; } = true; }
public sealed class FinancialPeriodClosing : Entity { public Guid AccountId { get; set; } public DateTime PeriodStart { get; set; } public DateTime PeriodEnd { get; set; } public DateTime ClosedAt { get; set; } public Guid ClosedByUserId { get; set; } public DateTime? ReopenedAt { get; set; } public Guid? ReopenedByUserId { get; set; } public string? ReopenReason { get; set; } public bool IsClosed { get; set; } = true; }
public sealed class FiscalDocumentRequest : Entity { public Guid AccountId { get; set; } public Guid? ClientId { get; set; } public Guid? ReceivableId { get; set; } public Guid? PaymentId { get; set; } public Guid? ReceiptId { get; set; } public FiscalRequestStatus Status { get; set; } = FiscalRequestStatus.Pending; public string FiscalDocumentType { get; set; } = ""; public DateTime RequestedAt { get; set; } public DateTime? IssuedAt { get; set; } public DateTime? CanceledAt { get; set; } public string? ExternalNumber { get; set; } public string? ExternalKeyMasked { get; set; } public string? ProviderName { get; set; } public string? Notes { get; set; } }
