using OrcaFacil.Domain.Common; using OrcaFacil.Domain.Enums; using OrcaFacil.Domain.ValueObjects; using System.Security.Cryptography; using System.Text;
namespace OrcaFacil.Domain.Entities;
public class UserAccount:Entity { public string Name{get;set;}=""; public string Email{get;set;}=""; public string? Phone{get;set;} public string PasswordHash{get;set;}=""; public UserRole Role{get;set;}=UserRole.User; public PlanType Plan{get;set;}=PlanType.Free; public bool IsActive{get;set;}=true; public bool IsBlocked{get;set;} public string? BlockReason{get;set;} public DateTime? AcceptedTermsAt{get;set;} public DateTime? AcceptedPrivacyAt{get;set;} public DateTime? LastLoginAt{get;set;} public DateTime? LastSeenAt{get;set;} }
public class IssuerProfile:Entity { public Guid UserId{get;set;} public string BusinessName{get;set;}=""; public string? DocumentNumber{get;set;} public string? Phone{get;set;} public string? Email{get;set;} public string? Address{get;set;} public string? City{get;set;} public string? PixKey{get;set;} public string? LogoPath{get;set;} }
public class Document:Entity { public Guid UserId{get;set;} public DocumentType Type{get;set;} public string Number{get;private set;}=""; public string Status{get;set;}="Draft"; public string ClientName{get;set;}=""; public string? ClientDocument{get;set;} public string? ClientPhone{get;set;} public string? ClientEmail{get;set;} public string? ClientCity{get;set;} public DateTime IssueDate{get;set;}=DateTime.UtcNow; public DateTime? ValidUntil{get;set;} public string? Notes{get;set;} public decimal Subtotal{get;private set;} public decimal Discount{get;set;} public decimal Total{get;private set;} public string? PublicToken{get;set;} public bool PublicEnabled{get;set;} public ClientDecision ClientDecision{get;set;}=ClientDecision.Pending; public DateTime? ClientDecisionAt{get;set;} public string? ClientDecisionNote{get;set;} public string? EvidenceHash{get;set;} public Guid? OriginBudgetId{get;set;} public string? OriginBudgetNumber{get;set;} public Guid? ConvertedReceiptId{get;set;} public string? ConvertedReceiptNumber{get;set;} public List<DocumentItem> Items{get;set;}=[]; public void IssueNumber(string number){ if(!string.IsNullOrWhiteSpace(Number)) throw new InvalidOperationException("Número emitido é imutável."); Number=number; } public void CalculateTotals(){ Subtotal=Items.Sum(i=>i.CalculateTotal()); Total=Math.Max(0, Subtotal-Discount); } public Document ConvertToReceipt(string receiptNumber){ if(Type!=DocumentType.Budget||ClientDecision!=ClientDecision.Approved) throw new InvalidOperationException("Somente orçamento aprovado pode virar recibo."); var receipt=new Document{UserId=UserId,Type=DocumentType.Receipt,ClientName=ClientName,ClientDocument=ClientDocument,ClientPhone=ClientPhone,ClientEmail=ClientEmail,ClientCity=ClientCity,IssueDate=DateTime.UtcNow,Notes=Notes,OriginBudgetId=Id,OriginBudgetNumber=Number}; receipt.IssueNumber(receiptNumber); receipt.Items=Items.Select(i=>new DocumentItem{Description=i.Description,Quantity=i.Quantity,UnitPrice=i.UnitPrice,Discount=i.Discount}).ToList(); receipt.CalculateTotals(); ConvertedReceiptId=receipt.Id; ConvertedReceiptNumber=receipt.Number; Status=BudgetStatus.Converted.ToString(); return receipt; } public string GenerateEvidenceHash(string actor,string userAgent){ var payload=$"{Id}|{PublicToken}|{ClientDecision}|{ClientDecisionAt:o}|{actor}|{userAgent}|{Total}"; return EvidenceHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(payload))); } }
public class DocumentItem:Entity { public Guid DocumentId{get;set;} public string Description{get;set;}=""; public decimal Quantity{get;set;} public decimal UnitPrice{get;set;} public decimal Discount{get;set;} public decimal Total{get;private set;} public decimal CalculateTotal()=>Total=Math.Max(0,Quantity*UnitPrice-Discount); }
public class PublicQuote:Entity { public string Token{get;set;}=new PublicToken().Value; public Guid OwnerUserId{get;set;} public Guid DocumentId{get;set;} public bool PublicEnabled{get;set;}=true; public DateTime? ExpiresAt{get;set;} public int ViewCount{get;set;} public DateTime? LastAccessAt{get;set;} public ClientDecision DecisionStatus{get;set;}=ClientDecision.Pending; public string? DecisionNote{get;set;} public DateTime? DecidedAt{get;set;} public string? DecidedByName{get;set;} public string? DecidedByDocument{get;set;} public string? DecidedByEmail{get;set;} public bool AcceptedTerms{get;set;} public string? EvidenceHash{get;set;} public string? UserAgent{get;set;} }
public class AuditLog:Entity { public Guid? UserId{get;set;} public string Action{get;set;}=""; public string EntityType{get;set;}=""; public string? EntityId{get;set;} public string? BeforeJson{get;set;} public string? AfterJson{get;set;} public string? MetadataJson{get;set;} public string? IpAddress{get;set;} public string? UserAgent{get;set;} }
public class SystemLog:Entity { public string Level{get;set;}="Info"; public string Type{get;set;}="Application"; public string Message{get;set;}=""; public Guid? UserId{get;set;} public string? UserEmail{get;set;} public string? MetadataJson{get;set;} public string? ErrorMessage{get;set;} public string? ErrorStack{get;set;} public string? Environment{get;set;} public string? Url{get;set;} }
public class SystemError:Entity { public string Message{get;set;}=""; public string? Stack{get;set;} public string? Code{get;set;} public string Severity{get;set;}="Error"; public Guid? UserId{get;set;} public string? ContextJson{get;set;} public bool Resolved{get;set;} public DateTime? ResolvedAt{get;set;} public Guid? ResolvedBy{get;set;} public string? AdminNote{get;set;} }
public class UserUsage:Entity { public Guid UserId{get;set;} public string Period{get;set;}=""; public int DocumentsCreated{get;set;} public int BudgetsCreated{get;set;} public int ReceiptsCreated{get;set;} public int PdfGenerated{get;set;} public int PublicLinksCreated{get;set;} public int BackupExports{get;set;} public int ChatbotQuestions{get;set;} }
public class Subscription:Entity { public Guid UserId{get;set;} public string Provider{get;set;}="Manual"; public SubscriptionStatus Status{get;set;} public PlanType Plan{get;set;} public string? BillingCycle{get;set;} public decimal Amount{get;set;} public DateTime? StartedAt{get;set;} public DateTime? ExpiresAt{get;set;} public DateTime? CancelledAt{get;set;} public DateTime? LastPaymentAt{get;set;} public string? ExternalCustomerId{get;set;} public string? ExternalSubscriptionId{get;set;} }
public class Payment:Entity { public Guid UserId{get;set;} public string Provider{get;set;}="Manual"; public PaymentStatus Status{get;set;} public PlanType Plan{get;set;} public string? BillingCycle{get;set;} public decimal Amount{get;set;} public string Currency{get;set;}="BRL"; public string? ExternalPaymentId{get;set;} public string? ExternalPreferenceId{get;set;} public string? PaymentMethod{get;set;} public string? PayerEmail{get;set;} public DateTime? ApprovedAt{get;set;} }
public class AdminSetting:Entity { public string Key{get;set;}=""; public string ValueJson{get;set;}="{}"; public Guid? UpdatedBy{get;set;} }
public class Notification:Entity { public Guid UserId{get;set;} public string Title{get;set;}=""; public string Message{get;set;}=""; public string Type{get;set;}="Info"; public bool Read{get;set;} public Guid? DocumentId{get;set;} }
