using OrcaFacil.Domain.Common;

namespace OrcaFacil.Domain.Entities;

public enum PartnerCategory { ServiceProvider, MaterialSupplier, OutsourcedTechnician, OutsourcedTeam, Commercial, Operational, Carrier, Other }
public enum PartnerStatus { Prospect, Active, Inactive, Blocked, UnderReview, Preferred }
public enum OutsourcingRequestStatus { Draft, Open, Quoted, Approved, Assigned, InProgress, Completed, Canceled, Rejected }
public enum OutsourcingQuoteStatus { Invited, Viewed, Submitted, Accepted, Rejected, Expired, Canceled }
public enum OutsourcingAssignmentStatus { Assigned, Accepted, Rejected, InProgress, PendingReview, Completed, Canceled, Disputed }
public enum PartnerDocumentStatus { Pending, Valid, Expired, Rejected, Revoked }
public enum PartnerEvidenceStatus { Submitted, Approved, Rejected, Archived }
public enum PartnerPaymentStatus { Pending, Approved, ConvertedToPayable, Paid, Rejected, Canceled }

public sealed class PartnerProfile : Entity { public Guid AccountId { get; set; } public Guid? SupplierId { get; set; } public string Name { get; set; } = ""; public string? LegalName { get; set; } public string? DocumentNumber { get; set; } public string? Email { get; set; } public string? Phone { get; set; } public string? WhatsApp { get; set; } public string? Website { get; set; } public PartnerCategory Category { get; set; } public PartnerStatus Status { get; set; } = PartnerStatus.Prospect; public decimal RatingAverage { get; set; } public string? Notes { get; set; } }
public sealed class PartnerContact : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public string Name { get; set; } = ""; public string Email { get; set; } = ""; public string? Phone { get; set; } public string? WhatsApp { get; set; } public string? Role { get; set; } public bool IsPrimary { get; set; } public bool CanAccessPortal { get; set; } public bool IsActive { get; set; } = true; }
public sealed class PartnerCapability : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid? ServiceCatalogItemId { get; set; } public string CapabilityName { get; set; } = ""; public string? Description { get; set; } public decimal DefaultCost { get; set; } public int DefaultLeadTimeDays { get; set; } public bool IsActive { get; set; } = true; }
public sealed class PartnerServiceArea : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public string City { get; set; } = ""; public string State { get; set; } = ""; public string? Region { get; set; } public decimal RadiusKm { get; set; } public bool IsActive { get; set; } = true; }
public sealed class PartnerDocument : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid FileAssetId { get; set; } public string DocumentType { get; set; } = ""; public PartnerDocumentStatus Status { get; set; } public DateTime? ExpirationDate { get; set; } public DateTime? ValidatedAt { get; set; } public Guid? ValidatedByUserId { get; set; } public string? Notes { get; set; } public string? RejectionReason { get; set; } }
public sealed class PartnerPortalUser : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid PartnerContactId { get; set; } public string EmailNormalized { get; set; } = ""; public bool IsActive { get; set; } = true; public DateTime? AccessRevokedAt { get; set; } public DateTime? LastLoginAt { get; set; } }
public sealed class PartnerPortalInvitation : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid PartnerContactId { get; set; } public string TokenHash { get; set; } = ""; public DateTime ExpiresAt { get; set; } public DateTime? AcceptedAt { get; set; } public DateTime? RevokedAt { get; set; } }
public sealed class PartnerPortalSession : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid PartnerPortalUserId { get; set; } public string TokenHash { get; set; } = ""; public DateTime ExpiresAt { get; set; } public DateTime? RevokedAt { get; set; } }
public sealed class PartnerPortalSecurityEvent : Entity { public Guid AccountId { get; set; } public Guid? PartnerId { get; set; } public string EventType { get; set; } = ""; public string? IpAddressHash { get; set; } public string? UserAgent { get; set; } public DateTime OccurredAt { get; set; } = DateTime.UtcNow; }
public sealed class OutsourcingRequest : Entity { public Guid AccountId { get; set; } public Guid? ClientId { get; set; } public Guid? WorkOrderId { get; set; } public Guid? DocumentId { get; set; } public Guid? BusinessUnitId { get; set; } public Guid RequestedByUserId { get; set; } public OutsourcingRequestStatus Status { get; set; } public string Title { get; set; } = ""; public string Description { get; set; } = ""; public DateTime? NeededByDate { get; set; } public decimal? BudgetLimit { get; set; } public string? InternalNotes { get; set; } public string? CancellationReason { get; set; } }
public sealed class OutsourcingRequestItem : Entity { public Guid AccountId { get; set; } public Guid OutsourcingRequestId { get; set; } public Guid? ServiceCatalogItemId { get; set; } public Guid? MaterialId { get; set; } public string Description { get; set; } = ""; public decimal Quantity { get; set; } public string Unit { get; set; } = "un"; public decimal? ExpectedUnitCost { get; set; } }
public sealed class OutsourcingQuote : Entity { public Guid AccountId { get; set; } public Guid OutsourcingRequestId { get; set; } public Guid PartnerId { get; set; } public OutsourcingQuoteStatus Status { get; set; } = OutsourcingQuoteStatus.Invited; public DateTime? SubmittedAt { get; set; } public DateTime ExpiresAt { get; set; } public decimal TotalAmount { get; set; } public int LeadTimeDays { get; set; } public string? PartnerNotes { get; set; } public string? InternalDecisionNotes { get; set; } }
public sealed class OutsourcingQuoteItem : Entity { public Guid AccountId { get; set; } public Guid OutsourcingQuoteId { get; set; } public string Description { get; set; } = ""; public decimal Quantity { get; set; } public decimal UnitAmount { get; set; } public decimal TotalAmount { get; set; } public string? Notes { get; set; } }
public sealed class OutsourcingAssignment : Entity { public Guid AccountId { get; set; } public Guid WorkOrderId { get; set; } public Guid OutsourcingRequestId { get; set; } public Guid OutsourcingQuoteId { get; set; } public Guid PartnerId { get; set; } public OutsourcingAssignmentStatus Status { get; set; } = OutsourcingAssignmentStatus.Assigned; public DateTime AssignedAt { get; set; } public DateTime? AcceptedAt { get; set; } public DateTime? RejectedAt { get; set; } public DateTime? StartedAt { get; set; } public DateTime? CompletedAt { get; set; } public DateTime? CanceledAt { get; set; } public decimal AgreedAmount { get; set; } public DateTime? AgreedDueDate { get; set; } public string? DecisionReason { get; set; } }
public sealed class PartnerWorkOrderUpdate : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid WorkOrderId { get; set; } public Guid OutsourcingAssignmentId { get; set; } public string UpdateType { get; set; } = ""; public string Message { get; set; } = ""; public bool IsVisibleToClient { get; set; } public DateTime SubmittedAt { get; set; } = DateTime.UtcNow; }
public sealed class PartnerWorkOrderEvidence : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid WorkOrderId { get; set; } public Guid FileAssetId { get; set; } public string EvidenceType { get; set; } = ""; public string? Description { get; set; } public bool IsVisibleToClient { get; set; } public DateTime SubmittedAt { get; set; } public DateTime? ReviewedAt { get; set; } public Guid? ReviewedByUserId { get; set; } public PartnerEvidenceStatus Status { get; set; } public string? RejectionReason { get; set; } }
public sealed class PartnerPaymentRequest : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid WorkOrderId { get; set; } public Guid OutsourcingAssignmentId { get; set; } public decimal Amount { get; set; } public PartnerPaymentStatus Status { get; set; } = PartnerPaymentStatus.Pending; public DateTime RequestedAt { get; set; } public DateTime? ApprovedAt { get; set; } public DateTime? PaidAt { get; set; } public Guid? PayableId { get; set; } public string? Notes { get; set; } public string? DecisionReason { get; set; } }
public sealed class PartnerCostSnapshot : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid WorkOrderId { get; set; } public Guid? DocumentId { get; set; } public Guid OutsourcingAssignmentId { get; set; } public decimal ContractedAmount { get; set; } public DateTime CapturedAt { get; set; } public Guid CapturedByUserId { get; set; } }
public sealed class PartnerRating : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid WorkOrderId { get; set; } public Guid RatedByUserId { get; set; } public int QualityScore { get; set; } public int PunctualityScore { get; set; } public int CommunicationScore { get; set; } public int DeadlineScore { get; set; } public int DocumentationScore { get; set; } public int CostBenefitScore { get; set; } public int ClientSatisfactionScore { get; set; } public string? Comment { get; set; } }
public sealed class PartnerTermsAcceptance : Entity { public Guid AccountId { get; set; } public Guid PartnerId { get; set; } public Guid PartnerPortalUserId { get; set; } public string TermsVersion { get; set; } = ""; public DateTime AcceptedAt { get; set; } public string IpAddressHash { get; set; } = ""; public string UserAgent { get; set; } = ""; }
