
-- Sprint 20 / Analytics V2.1: idempotent, tenant-scoped and data preserving.
CREATE TABLE IF NOT EXISTS orcafacil.business_goals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, business_unit_id uuid, team_id uuid, assigned_to_user_id uuid, name varchar(160) NOT NULL, goal_type integer NOT NULL, period_type integer NOT NULL, start_date date NOT NULL, end_date date NOT NULL, target_value numeric(18,2) NOT NULL CHECK(target_value >= 0), current_value numeric(18,2) NOT NULL DEFAULT 0, status integer NOT NULL DEFAULT 0, created_by_user_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false, CHECK(end_date >= start_date));
CREATE INDEX IF NOT EXISTS ix_business_goals_account_period ON orcafacil.business_goals(account_id,start_date,end_date);
CREATE TABLE IF NOT EXISTS orcafacil.goal_progress_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, goal_id uuid NOT NULL, reference_date date NOT NULL, current_value numeric(18,2) NOT NULL, progress_percentage numeric(8,2) NOT NULL, status integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_goal_progress_period ON orcafacil.goal_progress_snapshots(account_id,goal_id,reference_date);
CREATE TABLE IF NOT EXISTS orcafacil.analytics_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, frequency varchar(16) NOT NULL, period_start date NOT NULL, period_end date NOT NULL, calculated_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_analytics_snapshot_period ON orcafacil.analytics_snapshots(account_id,frequency,period_start,period_end);
CREATE TABLE IF NOT EXISTS orcafacil.analytics_snapshot_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, snapshot_id uuid NOT NULL, metric_code varchar(80) NOT NULL, value numeric(18,2) NOT NULL, explanation text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_analytics_snapshot_item ON orcafacil.analytics_snapshot_items(account_id,snapshot_id,metric_code);
CREATE TABLE IF NOT EXISTS orcafacil.forecast_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, forecast_type varchar(32) NOT NULL, reference_date date NOT NULL, horizon_days integer NOT NULL, forecast_value numeric(18,2) NOT NULL, confidence varchar(24) NOT NULL, explanation text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_forecast_snapshot_period ON orcafacil.forecast_snapshots(account_id,forecast_type,reference_date,horizon_days);
CREATE TABLE IF NOT EXISTS orcafacil.data_quality_findings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, rule_code varchar(80) NOT NULL, severity integer NOT NULL, entity_type varchar(40) NOT NULL, entity_id uuid NOT NULL, title text NOT NULL, description text NOT NULL, action_url varchar(500) NOT NULL, status integer NOT NULL DEFAULT 0, detected_at timestamptz NOT NULL, resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_data_quality_finding ON orcafacil.data_quality_findings(account_id,rule_code,entity_type,entity_id);
CREATE TABLE IF NOT EXISTS orcafacil.dashboard_widget_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, user_id uuid NOT NULL, widget_code varchar(80) NOT NULL, position integer NOT NULL, is_visible boolean NOT NULL DEFAULT true, is_favorite boolean NOT NULL DEFAULT false, default_period varchar(24) NOT NULL DEFAULT 'month', filters_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dashboard_widget_user ON orcafacil.dashboard_widget_preferences(account_id,user_id,widget_code);
INSERT INTO orcafacil.permissions(code,display_name,is_platform_permission) SELECT code,code,false FROM unnest(ARRAY['Analytics.View','Analytics.Executive','Analytics.Financial','Analytics.Operational','Analytics.Forecast','Analytics.Export','Goals.View','Goals.Manage','DataQuality.View','DataQuality.Manage','AccountHealth.View','ExecutiveAlerts.View','Dashboard.Customize']) code ON CONFLICT(code) DO NOTHING;
INSERT INTO orcafacil.role_permissions(role_id,permission_id,created_at,is_deleted) SELECT r.id,p.id,now(),false FROM orcafacil.roles r CROSS JOIN orcafacil.permissions p WHERE r.code IN ('Owner','Administrator') AND p.code IN ('Analytics.View','Analytics.Executive','Analytics.Financial','Analytics.Operational','Analytics.Forecast','Analytics.Export','Goals.View','Goals.Manage','DataQuality.View','DataQuality.Manage','AccountHealth.View','ExecutiveAlerts.View','Dashboard.Customize') ON CONFLICT(role_id,permission_id) DO NOTHING;
