-- Sprint 44 / V4.5. Idempotente e aditivo: não remove nem reescreve dados existentes.
CREATE SCHEMA IF NOT EXISTS orcafacil;
CREATE TABLE IF NOT EXISTS orcafacil.service_price_tables (id uuid PRIMARY KEY, account_id uuid NOT NULL, name varchar(160) NOT NULL, description varchar(1000), scope varchar(32) NOT NULL, customer_id uuid, segment_id uuid, contract_id uuid, valid_from date NOT NULL, valid_until date, is_active boolean NOT NULL DEFAULT true, version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false, CONSTRAINT ck_price_table_dates CHECK (valid_until IS NULL OR valid_until >= valid_from));
CREATE INDEX IF NOT EXISTS ix_price_tables_account_validity ON orcafacil.service_price_tables(account_id,is_active,valid_from,valid_until);
CREATE TABLE IF NOT EXISTS orcafacil.service_price_table_items (id uuid PRIMARY KEY, account_id uuid NOT NULL, service_price_table_id uuid NOT NULL, service_catalog_item_id uuid NOT NULL, base_price numeric(18,2) NOT NULL, minimum_price numeric(18,2) NOT NULL, maximum_price numeric(18,2), minimum_margin_percentage numeric(8,2) NOT NULL DEFAULT 0, maximum_discount_percentage numeric(8,2) NOT NULL DEFAULT 0, unit_code varchar(32) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false, CONSTRAINT ck_price_values CHECK (base_price >= 0 AND minimum_price >= 0 AND (maximum_price IS NULL OR maximum_price >= 0)));
CREATE UNIQUE INDEX IF NOT EXISTS ux_price_table_service ON orcafacil.service_price_table_items(account_id,service_price_table_id,service_catalog_item_id) WHERE NOT is_deleted;
CREATE TABLE IF NOT EXISTS orcafacil.pricing_margin_policies (id uuid PRIMARY KEY, account_id uuid NOT NULL, name varchar(160) NOT NULL, minimum_margin_percentage numeric(8,2) NOT NULL, target_margin_percentage numeric(8,2) NOT NULL, scope varchar(32) NOT NULL, scope_reference_id uuid, requires_approval_below_minimum boolean NOT NULL DEFAULT true, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false, CONSTRAINT ck_margin_policy CHECK (minimum_margin_percentage >= 0 AND target_margin_percentage >= minimum_margin_percentage));
CREATE TABLE IF NOT EXISTS orcafacil.pricing_discount_policies (id uuid PRIMARY KEY, account_id uuid NOT NULL, name varchar(160) NOT NULL, maximum_percentage_without_approval numeric(8,2) NOT NULL, maximum_amount_without_approval numeric(18,2) NOT NULL, approver_user_id uuid NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false, CONSTRAINT ck_discount_policy CHECK (maximum_percentage_without_approval BETWEEN 0 AND 100 AND maximum_amount_without_approval >= 0));
CREATE TABLE IF NOT EXISTS orcafacil.pricing_quote_snapshots (id uuid PRIMARY KEY, account_id uuid NOT NULL, quote_id uuid NOT NULL, sequence integer NOT NULL, payload_json jsonb NOT NULL, base_price numeric(18,2) NOT NULL, discount numeric(18,2) NOT NULL, total_cost numeric(18,2) NOT NULL, total_price numeric(18,2) NOT NULL, margin_percentage numeric(8,2) NOT NULL, created_by_user_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_quote_pricing_snapshot_sequence ON orcafacil.pricing_quote_snapshots(account_id,quote_id,sequence);
CREATE TABLE IF NOT EXISTS orcafacil.pricing_approval_events (id uuid PRIMARY KEY, account_id uuid NOT NULL, quote_id uuid NOT NULL, requested_by_user_id uuid NOT NULL, approver_user_id uuid NOT NULL, trigger varchar(80) NOT NULL, reason varchar(1000) NOT NULL, status varchar(24) NOT NULL, decision_reason varchar(1000), created_at timestamptz NOT NULL DEFAULT now(), decided_at timestamptz, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE INDEX IF NOT EXISTS ix_pricing_approvals_queue ON orcafacil.pricing_approval_events(account_id,status,created_at);
