-- Sprint 29 / V3.0. Migração exclusivamente aditiva e idempotente.
CREATE SCHEMA IF NOT EXISTS orcafacil;
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_packages (id uuid PRIMARY KEY,code varchar(80) NOT NULL,name varchar(160) NOT NULL,description text NOT NULL,category varchar(80) NOT NULL,target_segment varchar(100) NOT NULL,author varchar(120) NOT NULL DEFAULT 'OrçaFácil',is_active boolean NOT NULL DEFAULT false,is_published boolean NOT NULL DEFAULT false,current_version_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_versions (id uuid PRIMARY KEY,package_id uuid NOT NULL REFERENCES orcafacil.marketplace_packages(id),version varchar(40) NOT NULL,minimum_app_version varchar(40) NOT NULL,required_features_json jsonb NOT NULL DEFAULT '[]',required_plan_codes_json jsonb NOT NULL DEFAULT '[]',items_json jsonb NOT NULL,dependencies_json jsonb NOT NULL DEFAULT '[]',install_notes text,rollback_strategy varchar(80) NOT NULL,change_log text,is_published boolean NOT NULL DEFAULT false,published_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_items (id uuid PRIMARY KEY,package_version_id uuid NOT NULL REFERENCES orcafacil.marketplace_package_versions(id),item_type varchar(60) NOT NULL,item_code varchar(100) NOT NULL,manifest_json jsonb NOT NULL,display_order int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_dependencies (id uuid PRIMARY KEY,package_version_id uuid NOT NULL REFERENCES orcafacil.marketplace_package_versions(id),dependency_package_id uuid NOT NULL REFERENCES orcafacil.marketplace_packages(id),minimum_version varchar(40),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_installations (id uuid PRIMARY KEY,account_id uuid NOT NULL,package_id uuid NOT NULL REFERENCES orcafacil.marketplace_packages(id),package_version_id uuid NOT NULL REFERENCES orcafacil.marketplace_package_versions(id),installed_by_user_id uuid NOT NULL,status int NOT NULL,started_at timestamptz,completed_at timestamptz,failure_summary text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_installation_items (id uuid PRIMARY KEY,account_id uuid NOT NULL,installation_id uuid NOT NULL REFERENCES orcafacil.marketplace_package_installations(id),item_type varchar(60) NOT NULL,origin_key varchar(260) NOT NULL,created_entity_id uuid,status varchar(40) NOT NULL,was_created boolean NOT NULL DEFAULT false,is_deactivated boolean NOT NULL DEFAULT false,error_summary text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_installation_events (id uuid PRIMARY KEY,account_id uuid NOT NULL,installation_id uuid NOT NULL REFERENCES orcafacil.marketplace_package_installations(id),actor_user_id uuid NOT NULL,event_type varchar(100) NOT NULL,details_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_reviews (id uuid PRIMARY KEY,account_id uuid NOT NULL,package_id uuid NOT NULL REFERENCES orcafacil.marketplace_packages(id),rating int NOT NULL CHECK(rating BETWEEN 1 AND 5),comment varchar(2000),created_by_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_update_events (id uuid PRIMARY KEY,account_id uuid NOT NULL,installation_id uuid NOT NULL,from_version_id uuid NOT NULL,to_version_id uuid NOT NULL,status varchar(40) NOT NULL,actor_user_id uuid NOT NULL,details_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.marketplace_package_rollback_points (id uuid PRIMARY KEY,account_id uuid NOT NULL,installation_id uuid NOT NULL,package_version_id uuid NOT NULL,snapshot_json jsonb NOT NULL,created_by_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.vertical_templates (id uuid PRIMARY KEY,code varchar(100) NOT NULL,name varchar(160) NOT NULL,target_segment varchar(100) NOT NULL,is_active boolean NOT NULL DEFAULT false,current_version_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.vertical_template_versions (id uuid PRIMARY KEY,template_id uuid NOT NULL,version int NOT NULL,content_json jsonb NOT NULL,is_published boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.addon_catalog (id uuid PRIMARY KEY,code varchar(80) NOT NULL,name varchar(160) NOT NULL,description text NOT NULL,feature_codes_json jsonb NOT NULL DEFAULT '[]',required_plan_codes_json jsonb NOT NULL DEFAULT '[]',is_active boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.addon_installations (id uuid PRIMARY KEY,account_id uuid NOT NULL,addon_id uuid NOT NULL,installed_by_user_id uuid NOT NULL,is_active boolean NOT NULL DEFAULT false,installed_at timestamptz NOT NULL,removed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.addon_entitlements (id uuid PRIMARY KEY,account_id uuid NOT NULL,addon_installation_id uuid NOT NULL,feature_code varchar(120) NOT NULL,is_active boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.account_feature_bundles (id uuid PRIMARY KEY,account_id uuid NOT NULL,source_type varchar(40) NOT NULL,source_id uuid NOT NULL,feature_code varchar(120) NOT NULL,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.account_package_settings (id uuid PRIMARY KEY,account_id uuid NOT NULL,installation_id uuid NOT NULL,key varchar(120) NOT NULL,value_json jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.template_library_items (id uuid PRIMARY KEY,account_id uuid,code varchar(100) NOT NULL,name varchar(160) NOT NULL,type varchar(60) NOT NULL,target_segment varchar(100) NOT NULL,origin_package_id uuid,is_active boolean NOT NULL DEFAULT true,current_version_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.template_library_versions (id uuid PRIMARY KEY,template_id uuid NOT NULL,version_number int NOT NULL,content_json jsonb NOT NULL,preview_text text NOT NULL,is_published boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.template_import_jobs (id uuid PRIMARY KEY,account_id uuid NOT NULL,requested_by_user_id uuid NOT NULL,status varchar(40) NOT NULL,preview_json jsonb,result_json jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.template_export_jobs (id uuid PRIMARY KEY,account_id uuid NOT NULL,requested_by_user_id uuid NOT NULL,status varchar(40) NOT NULL,manifest_json jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.configuration_snapshots (id uuid PRIMARY KEY,account_id uuid NOT NULL,reason varchar(120) NOT NULL,created_by_user_id uuid NOT NULL,app_version varchar(40) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.configuration_snapshot_items (id uuid PRIMARY KEY,account_id uuid NOT NULL,snapshot_id uuid NOT NULL,item_type varchar(60) NOT NULL,item_key varchar(180) NOT NULL,configuration_json jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.setup_wizard_profiles (id uuid PRIMARY KEY,account_id uuid NOT NULL,user_id uuid NOT NULL,profile_json jsonb NOT NULL DEFAULT '{}',current_step int NOT NULL DEFAULT 0,is_completed boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.setup_wizard_steps (id uuid PRIMARY KEY,code varchar(80) NOT NULL,title varchar(160) NOT NULL,display_order int NOT NULL,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.setup_wizard_progress (id uuid PRIMARY KEY,account_id uuid NOT NULL,user_id uuid NOT NULL,profile_json jsonb NOT NULL DEFAULT '{}',current_step int NOT NULL DEFAULT 0,is_completed boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz,is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_marketplace_package_code ON orcafacil.marketplace_packages(code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_marketplace_version ON orcafacil.marketplace_package_versions(package_id,version);
CREATE UNIQUE INDEX IF NOT EXISTS ux_marketplace_origin ON orcafacil.marketplace_package_installation_items(account_id,installation_id,origin_key);
CREATE INDEX IF NOT EXISTS ix_marketplace_installations_account ON orcafacil.marketplace_package_installations(account_id,created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_marketplace_review ON orcafacil.marketplace_package_reviews(account_id,package_id) WHERE is_deleted=false;
CREATE UNIQUE INDEX IF NOT EXISTS ux_addon_catalog_code ON orcafacil.addon_catalog(code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_addon_active ON orcafacil.addon_installations(account_id,addon_id) WHERE is_active=true AND is_deleted=false;
CREATE UNIQUE INDEX IF NOT EXISTS ux_addon_entitlement ON orcafacil.addon_entitlements(account_id,feature_code) WHERE is_active=true AND is_deleted=false;
CREATE UNIQUE INDEX IF NOT EXISTS ux_setup_wizard_progress ON orcafacil.setup_wizard_progress(account_id,user_id) WHERE is_deleted=false;
INSERT INTO orcafacil.permissions(code,display_name,is_platform_permission) SELECT code,code,false FROM unnest(ARRAY['Marketplace.View','Marketplace.Install','Marketplace.Rollback','Marketplace.Update','Marketplace.Review','Marketplace.AdminView','Marketplace.AdminManage','Templates.LibraryView','Templates.LibraryManage','Configuration.Export','Configuration.Import','SetupWizard.Use','Addons.View','Addons.Manage','Addons.Install','Addons.Remove','Entitlements.Manage']) code ON CONFLICT(code) DO NOTHING;
-- Catálogo real: somente definições publicadas; nenhum cliente, OS, orçamento ou lançamento operacional é criado.
WITH catalog(code,name,description,category,segment,items) AS (VALUES
('assistencia-tecnica','Assistência Técnica','Configura campos, checklists e fluxo auditável para ordens de serviço.','Setores/Verticais','Assistência técnica','[{"type":"CustomField","code":"equipamento-modelo","name":"Modelo do equipamento","configuration":{"entityType":"WorkOrder","fieldType":"ShortText"}},{"type":"Checklist","code":"diagnostico","name":"Diagnóstico técnico","configuration":{"targetEntityType":"WorkOrder","items":["Identificar equipamento","Registrar sintomas","Anexar evidências","Informar diagnóstico"]}},{"type":"Checklist","code":"conclusao","name":"Conclusão do atendimento","configuration":{"targetEntityType":"WorkOrder","items":["Validar reparo","Registrar evidências finais","Obter aceite"]}},{"type":"Workflow","code":"fluxo-os","name":"Fluxo de assistência técnica","configuration":{"entityType":"WorkOrder","states":["Aberta","Agendada","Em diagnóstico","Aguardando aprovação","Em execução","Concluída","Cancelada"]}},{"type":"Template","code":"proposta-reparo","name":"Proposta de reparo","configuration":{"templateType":"Proposta","targetSegment":"Assistência técnica","preview":"Diagnóstico, solução proposta, peças, mão de obra, prazo e garantia."}}]'::jsonb),
('prestadora-servicos','Prestadora de Serviços','Configura pipeline comercial, execução e acompanhamento de produtividade.','Comercial','Serviços','[{"type":"Pipeline","code":"comercial-simples","name":"Pipeline comercial simples","configuration":{"entityType":"CommercialLead","stages":["Novo","Qualificado","Proposta","Fechado"]}},{"type":"Checklist","code":"execucao-servico","name":"Execução do serviço","configuration":{"targetEntityType":"WorkOrder","items":["Confirmar escopo","Executar atividade","Registrar evidência","Obter aceite"]}},{"type":"Template","code":"follow-up","name":"Follow-up comercial","configuration":{"templateType":"E-mail","targetSegment":"Serviços","preview":"Acompanhamento objetivo da proposta e próximos passos."}}]'::jsonb),
('manutencao-preventiva','Manutenção Preventiva','Configura checklists, fluxo preventivo e modelo de renovação.','Contratos','Manutenção','[{"type":"Checklist","code":"manutencao-preventiva","name":"Manutenção preventiva","configuration":{"targetEntityType":"WorkOrder","items":["Inspeção visual","Medições técnicas","Ajustes","Evidências e recomendações"]}},{"type":"Workflow","code":"os-preventiva","name":"Fluxo de OS preventiva","configuration":{"entityType":"WorkOrder","states":["Planejada","Agendada","Em execução","Concluída"]}},{"type":"Template","code":"renovacao-preventiva","name":"Renovação de manutenção","configuration":{"templateType":"Contrato","targetSegment":"Manutenção","preview":"Escopo recorrente, periodicidade, SLA, reajuste e renovação."}}]'::jsonb),
('crm-pos-venda','CRM e Pós-venda','Configura pipeline e modelos para relacionamento e satisfação.','CRM','Pós-venda','[{"type":"Pipeline","code":"relacionamento","name":"Relacionamento pós-venda","configuration":{"entityType":"Client","stages":["Ativo","Acompanhar","Em risco","Recuperado"]}},{"type":"Template","code":"pesquisa-satisfacao","name":"Pesquisa de satisfação","configuration":{"templateType":"Formulário","targetSegment":"Pós-venda","preview":"Avaliação de satisfação, recomendação e comentário opcional."}}]'::jsonb),
('financeiro-gerencial','Financeiro Gerencial','Configura referências gerenciais para acompanhamento financeiro.','Financeiro','Gestão','[{"type":"Template","code":"dre-gerencial","name":"Modelo de DRE gerencial","configuration":{"templateType":"Relatório","targetSegment":"Gestão","preview":"Receita, custos variáveis, margem de contribuição e despesas operacionais."}},{"type":"Template","code":"alerta-financeiro","name":"Alerta financeiro","configuration":{"templateType":"Automação","targetSegment":"Gestão","preview":"Notificação de vencimento conforme regras revisadas pela conta."}}]'::jsonb))
INSERT INTO orcafacil.marketplace_packages(id,code,name,description,category,target_segment,author,is_active,is_published,created_at,is_deleted)
SELECT md5(code)::uuid,code,name,description,category,segment,'OrçaFácil',true,true,now(),false FROM catalog ON CONFLICT(code) DO UPDATE SET name=excluded.name,description=excluded.description,category=excluded.category,target_segment=excluded.target_segment,updated_at=now() WHERE orcafacil.marketplace_packages.is_deleted=false;
WITH catalog(code,items) AS (VALUES
('assistencia-tecnica','[{"type":"CustomField","code":"equipamento-modelo","name":"Modelo do equipamento","configuration":{"entityType":"WorkOrder","fieldType":"ShortText"}},{"type":"Checklist","code":"diagnostico","name":"Diagnóstico técnico","configuration":{"targetEntityType":"WorkOrder","items":["Identificar equipamento","Registrar sintomas","Anexar evidências","Informar diagnóstico"]}},{"type":"Checklist","code":"conclusao","name":"Conclusão do atendimento","configuration":{"targetEntityType":"WorkOrder","items":["Validar reparo","Registrar evidências finais","Obter aceite"]}},{"type":"Workflow","code":"fluxo-os","name":"Fluxo de assistência técnica","configuration":{"entityType":"WorkOrder","states":["Aberta","Agendada","Em diagnóstico","Aguardando aprovação","Em execução","Concluída","Cancelada"]}},{"type":"Template","code":"proposta-reparo","name":"Proposta de reparo","configuration":{"templateType":"Proposta","targetSegment":"Assistência técnica","preview":"Diagnóstico, solução proposta, peças, mão de obra, prazo e garantia."}}]'::jsonb),
('prestadora-servicos','[{"type":"Pipeline","code":"comercial-simples","name":"Pipeline comercial simples","configuration":{"entityType":"CommercialLead","stages":["Novo","Qualificado","Proposta","Fechado"]}},{"type":"Checklist","code":"execucao-servico","name":"Execução do serviço","configuration":{"targetEntityType":"WorkOrder","items":["Confirmar escopo","Executar atividade","Registrar evidência","Obter aceite"]}},{"type":"Template","code":"follow-up","name":"Follow-up comercial","configuration":{"templateType":"E-mail","targetSegment":"Serviços","preview":"Acompanhamento objetivo da proposta e próximos passos."}}]'::jsonb),
('manutencao-preventiva','[{"type":"Checklist","code":"manutencao-preventiva","name":"Manutenção preventiva","configuration":{"targetEntityType":"WorkOrder","items":["Inspeção visual","Medições técnicas","Ajustes","Evidências e recomendações"]}},{"type":"Workflow","code":"os-preventiva","name":"Fluxo de OS preventiva","configuration":{"entityType":"WorkOrder","states":["Planejada","Agendada","Em execução","Concluída"]}},{"type":"Template","code":"renovacao-preventiva","name":"Renovação de manutenção","configuration":{"templateType":"Contrato","targetSegment":"Manutenção","preview":"Escopo recorrente, periodicidade, SLA, reajuste e renovação."}}]'::jsonb),
('crm-pos-venda','[{"type":"Pipeline","code":"relacionamento","name":"Relacionamento pós-venda","configuration":{"entityType":"Client","stages":["Ativo","Acompanhar","Em risco","Recuperado"]}},{"type":"Template","code":"pesquisa-satisfacao","name":"Pesquisa de satisfação","configuration":{"templateType":"Formulário","targetSegment":"Pós-venda","preview":"Avaliação de satisfação, recomendação e comentário opcional."}}]'::jsonb),
('financeiro-gerencial','[{"type":"Template","code":"dre-gerencial","name":"Modelo de DRE gerencial","configuration":{"templateType":"Relatório","targetSegment":"Gestão","preview":"Receita, custos variáveis, margem de contribuição e despesas operacionais."}},{"type":"Template","code":"alerta-financeiro","name":"Alerta financeiro","configuration":{"templateType":"Automação","targetSegment":"Gestão","preview":"Notificação de vencimento conforme regras revisadas pela conta."}}]'::jsonb))
INSERT INTO orcafacil.marketplace_package_versions(id,package_id,version,minimum_app_version,required_features_json,required_plan_codes_json,items_json,dependencies_json,install_notes,rollback_strategy,change_log,is_published,published_at,created_at,is_deleted)
SELECT md5(code||':1.0.0')::uuid,md5(code)::uuid,'1.0.0','3.0.0','[]','[]',items,'[]','Revise a prévia e confirme os itens antes da instalação.','DeactivateInstalledConfiguration','Versão inicial segura.',true,now(),now(),false FROM catalog ON CONFLICT(package_id,version) DO NOTHING;
UPDATE orcafacil.marketplace_packages p SET current_version_id=md5(p.code||':1.0.0')::uuid WHERE p.code IN ('assistencia-tecnica','prestadora-servicos','manutencao-preventiva','crm-pos-venda','financeiro-gerencial');
INSERT INTO orcafacil.role_permissions(role_id,permission_id,created_at,is_deleted)
SELECT r.id,p.id,now(),false FROM orcafacil.roles r CROSS JOIN orcafacil.permissions p
WHERE r.code IN ('Owner','Administrator') AND p.code IN ('Marketplace.View','Marketplace.Install','Marketplace.Rollback','Marketplace.Update','Marketplace.Review','Templates.LibraryView','Configuration.Export','Configuration.Import','SetupWizard.Use','Addons.View','Addons.Install','Addons.Remove')
ON CONFLICT(role_id,permission_id) DO NOTHING;
