using System.ComponentModel.DataAnnotations;using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.EntityFrameworkCore;using OrcaFacil.Domain.Entities;using OrcaFacil.Persistence;
namespace OrcaFacil.Web.Pages.SuperAdmin.Clients;
[Authorize(Policy="SuperAdminOnly")]public sealed class EditModel(OrcaFacilDbContext db):PageModel{[BindProperty]public InputModel Input{get;set;}=new();public sealed class InputModel{public Guid Id{get;set;}[Required,StringLength(180)]public string Name{get;set;}="";[Required,EmailAddress]public string Email{get;set;}="";[Required,StringLength(40)]public string Plan{get;set;}="FREE";[Required,StringLength(32)]public string FinancialStatus{get;set;}="Current";[StringLength(160)]public string? Responsible{get;set;}[StringLength(2000)]public string? Notes{get;set;}}
public async Task<IActionResult> OnGetAsync(Guid id,CancellationToken ct){var x=await db.BusinessAccounts.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&!x.IsDeleted,ct);if(x is null)return NotFound();Input=new(){Id=x.Id,Name=x.DisplayName,Email=x.Email,Plan=x.CurrentPlanCode,FinancialStatus=x.FinancialStatus,Responsible=x.ResponsibleName,Notes=x.InternalNotes};return Page();}
public async Task<IActionResult> OnPostAsync(CancellationToken ct){if(!ModelState.IsValid)return Page();var x=await db.BusinessAccounts.SingleOrDefaultAsync(x=>x.Id==Input.Id&&!x.IsDeleted,ct);if(x is null)return NotFound();x.DisplayName=Input.Name.Trim();x.Email=Input.Email.Trim().ToLowerInvariant();x.CurrentPlanCode=Input.Plan.Trim().ToUpperInvariant();x.FinancialStatus=Input.FinancialStatus;x.ResponsibleName=Input.Responsible?.Trim();x.InternalNotes=Input.Notes?.Trim();x.Touch();Audit(x,"GlobalClientUpdated","Dados cadastrais atualizados.");await db.SaveChangesAsync(ct);return RedirectToPage("Details",new{id=x.Id});}
public async Task<IActionResult> OnPostBlockAsync(Guid id,string reason,CancellationToken ct){var x=await Find(id,ct);if(x is null)return NotFound();x.Block(reason);Audit(x,"GlobalClientBlocked",reason);await db.SaveChangesAsync(ct);return RedirectToPage(new{id});}
public async Task<IActionResult> OnPostReactivateAsync(Guid id,CancellationToken ct){var x=await Find(id,ct);if(x is null)return NotFound();x.Activate();Audit(x,"GlobalClientReactivated","Conta reativada.");await db.SaveChangesAsync(ct);return RedirectToPage(new{id});}
public async Task<IActionResult> OnPostDeleteAsync(Guid id,CancellationToken ct){var x=await Find(id,ct);if(x is null)return NotFound();x.MarkAsDeleted();Audit(x,"GlobalClientSoftDeleted","Exclusão lógica executada.");await db.SaveChangesAsync(ct);return RedirectToPage("Index");}
private Task<BusinessAccount?>Find(Guid id,CancellationToken ct)=>db.BusinessAccounts.SingleOrDefaultAsync(x=>x.Id==id&&!x.IsDeleted,ct);private void Audit(BusinessAccount x,string action,string summary)=>db.AccountModuleAuditLogs.Add(new(){AccountId=x.Id,ActorUserId=Guid.TryParse(User.FindFirstValue("user_id"),out var actor)?actor:Guid.Empty,Action=action,EntityType=nameof(BusinessAccount),EntityId=x.Id.ToString(),Summary=summary,CorrelationId=HttpContext.TraceIdentifier});}
