using System.ComponentModel.DataAnnotations; using System.Security.Claims; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.Mvc.RazorPages; using Microsoft.EntityFrameworkCore; using OrcaFacil.Application.Auth; using OrcaFacil.Domain.Entities; using OrcaFacil.Domain.Enums; using OrcaFacil.Persistence;
namespace OrcaFacil.Web.Pages.SuperAdmin.Clients;
[Authorize(Policy="SuperAdminOnly")]
public sealed class NewModel(OrcaFacilDbContext db,LoginIdentifierService identifiers):PageModel
{
 [BindProperty]public InputModel Input{get;set;}=new(); public sealed class InputModel{[Required,StringLength(180)]public string LegalName{get;set;}="";[StringLength(180)]public string? TradeName{get;set;}[Required]public string Document{get;set;}="";[Required,EmailAddress]public string Email{get;set;}="";[StringLength(40)]public string? Phone{get;set;}[StringLength(160)]public string? Responsible{get;set;}[StringLength(120)]public string? City{get;set;}[StringLength(2,MinimumLength=2)]public string? State{get;set;}}
 public async Task<IActionResult> OnPostAsync(CancellationToken ct){if(!ModelState.IsValid)return Page();NormalizedLoginIdentifier document;try{document=identifiers.Normalize(Input.Document);}catch(ArgumentException ex){ModelState.AddModelError("Input.Document",ex.Message);return Page();}if(document.Kind==LoginIdentifierKind.Email){ModelState.AddModelError("Input.Document","Informe um CPF ou CNPJ.");return Page();}if(await db.BusinessAccounts.AnyAsync(x=>x.DocumentNumber==document.Value&&!x.IsDeleted,ct)){ModelState.AddModelError("Input.Document","Já existe um cliente com este documento.");return Page();}var account=new BusinessAccount{DisplayName=(Input.TradeName??Input.LegalName).Trim(),LegalName=Input.LegalName.Trim(),TradeName=Input.TradeName?.Trim(),DocumentType=document.Kind==LoginIdentifierKind.Cpf?BrazilianDocumentType.CPF:BrazilianDocumentType.CNPJ,DocumentNumber=document.Value,PersonType=document.Kind==LoginIdentifierKind.Cpf?PersonType.Individual:PersonType.Company,Email=Input.Email.Trim().ToLowerInvariant(),Phone=Input.Phone?.Trim(),ResponsibleName=Input.Responsible?.Trim(),City=Input.City?.Trim(),State=Input.State?.Trim().ToUpperInvariant()};db.BusinessAccounts.Add(account);db.AccountModuleAuditLogs.Add(new(){AccountId=account.Id,ActorUserId=Actor(),Action="GlobalClientCreated",EntityType=nameof(BusinessAccount),EntityId=account.Id.ToString(),Summary="Cliente criado pela administração global.",CorrelationId=HttpContext.TraceIdentifier});await db.SaveChangesAsync(ct);TempData["Success"]="Cliente criado com sucesso.";return RedirectToPage("Details",new{id=account.Id});}
 private Guid Actor()=>Guid.TryParse(User.FindFirstValue("user_id"),out var id)?id:Guid.Empty;
}
