using OrcaFacil.Application.Abstractions; using OrcaFacil.Domain.Entities; using OrcaFacil.Domain.Enums; using OrcaFacil.Domain.ValueObjects; using OrcaFacil.Shared;
namespace OrcaFacil.Application.UseCases;
public record RegisterUserCommand(string Name,string Email,string Password,bool AcceptTerms,bool AcceptPrivacy);
public record LoginUserCommand(string Email,string Password);
public record SaveIssuerProfileCommand(Guid UserId,string BusinessName,string? DocumentNumber,string? Phone,string? Email,string? Address,string? City,string? PixKey);
public record CreateDocumentCommand(Guid UserId,DocumentType Type,string Number,string ClientName,IReadOnlyList<DocumentItemDto> Items,decimal Discount,string? Notes);
public record ApprovePublicQuoteCommand(string Token,string Name,string? Document,string? Email,string? Note,bool AcceptedTerms,string UserAgent);
public class AuthService(IRepository<UserAccount> users, IPasswordHasher hasher, IUnitOfWork uow){ public async Task<Result<Guid>> RegisterAsync(RegisterUserCommand c,CancellationToken ct=default){ _=new Email(c.Email); if(!c.AcceptTerms||!c.AcceptPrivacy) return Result<Guid>.Fail("Termos e privacidade são obrigatórios."); if(users.Query().Any(u=>u.Email==c.Email.ToLowerInvariant())) return Result<Guid>.Fail("E-mail já cadastrado."); var u=new UserAccount{Name=c.Name,Email=c.Email.ToLowerInvariant(),PasswordHash=hasher.Hash(c.Password),AcceptedTermsAt=DateTime.UtcNow,AcceptedPrivacyAt=DateTime.UtcNow}; await users.AddAsync(u,ct); await uow.SaveChangesAsync(ct); return Result<Guid>.Ok(u.Id);} public Result<Guid> Login(LoginUserCommand c){ var u=users.Query().SingleOrDefault(x=>x.Email==c.Email.ToLowerInvariant()); if(u is null||!hasher.Verify(c.Password,u.PasswordHash)) return Result<Guid>.Fail("Credenciais inválidas."); if(u.IsBlocked) return Result<Guid>.Fail("Usuário bloqueado."); u.LastLoginAt=DateTime.UtcNow; return Result<Guid>.Ok(u.Id);} }
public class DocumentService(IRepository<Document> documents,IRepository<PublicQuote> quotes,IUnitOfWork uow){ public async Task<Result<Guid>> CreateAsync(CreateDocumentCommand c,CancellationToken ct=default){ var d=new Document{UserId=c.UserId,Type=c.Type,ClientName=c.ClientName,Discount=c.Discount,Notes=c.Notes}; d.IssueNumber(c.Number); d.Items=c.Items.Select(i=>new DocumentItem{Description=i.Description,Quantity=i.Quantity,UnitPrice=i.UnitPrice,Discount=i.Discount}).ToList(); d.CalculateTotals(); await documents.AddAsync(d,ct); await uow.SaveChangesAsync(ct); return Result<Guid>.Ok(d.Id);} public async Task<Result<string>> GeneratePublicLinkAsync(Guid userId,Guid documentId,CancellationToken ct=default){ var d=await documents.GetAsync(documentId,ct); if(d is null||d.UserId!=userId) return Result<string>.Fail("Documento não encontrado."); d.PublicToken=new PublicToken().Value; d.PublicEnabled=true; var q=new PublicQuote{DocumentId=d.Id,OwnerUserId=userId,Token=d.PublicToken,ExpiresAt=DateTime.UtcNow.AddDays(30)}; await quotes.AddAsync(q,ct); await uow.SaveChangesAsync(ct); return Result<string>.Ok(q.Token);} public async Task<Result> ApproveAsync(ApprovePublicQuoteCommand c,CancellationToken ct=default){ var q=quotes.Query().SingleOrDefault(x=>x.Token==c.Token&&x.PublicEnabled); if(q is null) return Result.Fail("Link inválido."); var d=await documents.GetAsync(q.DocumentId,ct); if(d is null) return Result.Fail("Documento indisponível."); q.DecisionStatus=ClientDecision.Approved; q.DecisionNote=c.Note; q.DecidedAt=DateTime.UtcNow; q.DecidedByName=c.Name; q.DecidedByDocument=c.Document; q.DecidedByEmail=c.Email; q.AcceptedTerms=c.AcceptedTerms; q.UserAgent=c.UserAgent; d.ClientDecision=ClientDecision.Approved; d.ClientDecisionAt=q.DecidedAt; d.Status=BudgetStatus.Approved.ToString(); q.EvidenceHash=d.GenerateEvidenceHash(c.Name,c.UserAgent); await uow.SaveChangesAsync(ct); return Result.Ok();} }
public class PlanLimitService { public bool CanCreateDocument(PlanType plan,int monthlyCount,int freeLimit=5)=>plan==PlanType.Pro||monthlyCount<freeLimit; public bool PdfHasWatermark(PlanType plan)=>plan==PlanType.Free; }
