using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using OrcaFacil.Application.Services;using OrcaFacil.Web.ViewModels.Services;
namespace OrcaFacil.Web.Pages.Services;
[Authorize] public sealed class EditModel(IServiceCatalogApplicationService catalog,IServiceUnitCatalog units):PageModel
{
    public Guid Id{get;private set;} [BindProperty]public ServiceEditorInput Input{get;set;}=new();[BindProperty]public string? PriceChangeReason{get;set;}public ServiceEditorViewModel Editor{get;private set;}=new();
    public async Task<IActionResult> OnGetAsync(Guid id,CancellationToken ct){var details=await catalog.GetAsync(id,ct);if(details is null)return NotFound();Id=id;var x=details.Item;Input=new(){Name=x.Name,Code=x.Code,CategoryId=x.CategoryId,Description=x.Description,UnitCode=x.UnitCode,StandardPrice=x.StandardPrice,EstimatedCost=x.EstimatedCost,DesiredMarginPercentage=x.DesiredMarginPercentage,SuggestedDurationMinutes=x.SuggestedDurationMinutes,DefaultDeliveryTerm=x.DefaultDeliveryTerm,DefaultNotes=x.DefaultNotes,Tags=x.Tags,InternalNotes=x.InternalNotes,IsFavorite=x.IsFavorite,IsActive=x.IsActive,IsRecurring=x.IsRecurring,IsRecommended=x.IsRecommended,Version=x.Version};Build();return Page();}
    public async Task<IActionResult> OnPostAsync(Guid id,CancellationToken ct){Id=id;if(!units.Contains(Input.UnitCode))ModelState.AddModelError("Input.UnitCode","Unidade inválida.");if(!ModelState.IsValid){Build();return Page();}var result=await catalog.UpdateAsync(id,Input.Version,new(Input.Name,Input.Code,Input.Description,Input.CategoryId,Input.UnitCode,Input.StandardPrice,Input.EstimatedCost,Input.DesiredMarginPercentage,Input.SuggestedDurationMinutes,Input.DefaultDeliveryTerm,Input.DefaultNotes,Input.Tags,Input.InternalNotes,Input.IsFavorite,Input.IsActive,Input.IsRecurring,Input.IsRecommended),PriceChangeReason,ct);if(result.Code==ServiceCatalogResultCode.NotFound)return NotFound();if(result.Code!=ServiceCatalogResultCode.Success){ModelState.AddModelError("",result.Message??"Não foi possível salvar.");Build();return Page();}TempData["Success"]="Serviço atualizado.";return RedirectToPage("Details",new{id});}
    private void Build()=>Editor=new(){Input=Input,UnitOptions=units.GetAll(),IsEditing=true,RequiresPriceChangeReason=true,PriceChangeReason=PriceChangeReason,PreviewTitle="Resumo",SubmitLabel="Salvar alterações"};
}
