using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace OrcaFacil.Persistence.Migrations;
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.EnsureSchema("orcafacil");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.users (id uuid PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, phone text NULL, password_hash text NOT NULL, role text NOT NULL, plan text NOT NULL, is_active boolean NOT NULL, is_blocked boolean NOT NULL, block_reason text NULL, accepted_terms_at timestamptz NULL, accepted_privacy_at timestamptz NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL, last_login_at timestamptz NULL, last_seen_at timestamptz NULL);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.issuer_profiles (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES orcafacil.users(id), business_name text NOT NULL, document_number text NULL, phone text NULL, email text NULL, address text NULL, city text NULL, pix_key text NULL, logo_path text NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL); CREATE UNIQUE INDEX IF NOT EXISTS ux_issuer_profiles_user_id ON orcafacil.issuer_profiles(user_id);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.documents (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES orcafacil.users(id), type text NOT NULL, number text NOT NULL, status text NOT NULL, client_name text NOT NULL, client_document text NULL, client_phone text NULL, client_email text NULL, client_city text NULL, issue_date timestamptz NOT NULL, valid_until timestamptz NULL, notes text NULL, subtotal numeric(18,2) NOT NULL, discount numeric(18,2) NOT NULL, total numeric(18,2) NOT NULL, public_token text NULL, public_enabled boolean NOT NULL, client_decision text NOT NULL, client_decision_at timestamptz NULL, client_decision_note text NULL, evidence_hash text NULL, origin_budget_id uuid NULL, origin_budget_number text NULL, converted_receipt_id uuid NULL, converted_receipt_number text NULL, is_deleted boolean NOT NULL DEFAULT false, deleted_at timestamptz NULL, deleted_by uuid NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL); CREATE UNIQUE INDEX IF NOT EXISTS ux_documents_user_type_number ON orcafacil.documents(user_id,type,number); CREATE INDEX IF NOT EXISTS ix_documents_user_id ON orcafacil.documents(user_id); CREATE INDEX IF NOT EXISTS ix_documents_created_at ON orcafacil.documents(created_at); CREATE INDEX IF NOT EXISTS ix_documents_status ON orcafacil.documents(status);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.document_items (id uuid PRIMARY KEY, document_id uuid NOT NULL REFERENCES orcafacil.documents(id) ON DELETE CASCADE, description text NOT NULL, quantity numeric(18,2) NOT NULL, unit_price numeric(18,2) NOT NULL, discount numeric(18,2) NOT NULL, total numeric(18,2) NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL); CREATE INDEX IF NOT EXISTS ix_document_items_document_id ON orcafacil.document_items(document_id);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.public_quotes (id uuid PRIMARY KEY, token text NOT NULL UNIQUE, owner_user_id uuid NOT NULL REFERENCES orcafacil.users(id), document_id uuid NOT NULL REFERENCES orcafacil.documents(id), public_enabled boolean NOT NULL, expires_at timestamptz NULL, view_count integer NOT NULL, last_access_at timestamptz NULL, decision_status text NOT NULL, decision_note text NULL, decided_at timestamptz NULL, decided_by_name text NULL, decided_by_document text NULL, decided_by_email text NULL, accepted_terms boolean NOT NULL, evidence_hash text NULL, user_agent text NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.user_usage (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES orcafacil.users(id), period text NOT NULL, documents_created integer NOT NULL, budgets_created integer NOT NULL, receipts_created integer NOT NULL, pdf_generated integer NOT NULL, public_links_created integer NOT NULL, backup_exports integer NOT NULL, chatbot_questions integer NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL); CREATE UNIQUE INDEX IF NOT EXISTS ux_user_usage_user_period ON orcafacil.user_usage(user_id,period);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.subscriptions (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES orcafacil.users(id), provider text NOT NULL, status text NOT NULL, plan text NOT NULL, billing_cycle text NULL, amount numeric(18,2) NOT NULL, started_at timestamptz NULL, expires_at timestamptz NULL, cancelled_at timestamptz NULL, last_payment_at timestamptz NULL, external_customer_id text NULL, external_subscription_id text NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL); CREATE TABLE IF NOT EXISTS orcafacil.payments (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES orcafacil.users(id), provider text NOT NULL, status text NOT NULL, plan text NOT NULL, billing_cycle text NULL, amount numeric(18,2) NOT NULL, currency text NOT NULL, external_payment_id text NULL, external_preference_id text NULL, payment_method text NULL, payer_email text NULL, created_at timestamptz NOT NULL, approved_at timestamptz NULL, updated_at timestamptz NULL);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.admin_settings (id uuid PRIMARY KEY, key text NOT NULL UNIQUE, value_json jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL, updated_by uuid NULL); CREATE TABLE IF NOT EXISTS orcafacil.notifications (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES orcafacil.users(id), title text NOT NULL, message text NOT NULL, type text NOT NULL, read boolean NOT NULL, document_id uuid NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL);");
        migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS orcafacil.audit_logs (id uuid PRIMARY KEY, user_id uuid NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text NULL, before_json jsonb NULL, after_json jsonb NULL, metadata_json jsonb NULL, ip_address text NULL, user_agent text NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL); CREATE TABLE IF NOT EXISTS orcafacil.system_logs (id uuid PRIMARY KEY, level text NOT NULL, type text NOT NULL, message text NOT NULL, user_id uuid NULL, user_email text NULL, metadata_json jsonb NULL, error_message text NULL, error_stack text NULL, environment text NULL, url text NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL); CREATE TABLE IF NOT EXISTS orcafacil.system_errors (id uuid PRIMARY KEY, message text NOT NULL, stack text NULL, code text NULL, severity text NOT NULL, user_id uuid NULL, context_json jsonb NULL, resolved boolean NOT NULL, resolved_at timestamptz NULL, resolved_by uuid NULL, admin_note text NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL);");
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.Sql("DROP SCHEMA IF EXISTS orcafacil CASCADE;"); }
}
