-- Sprint 33 / V3.4 - Growth SaaS. Additive and idempotent; never removes customer data.
CREATE SCHEMA IF NOT EXISTS orcafacil;

CREATE TABLE IF NOT EXISTS orcafacil.growth_leads (
 id uuid PRIMARY KEY, tenant_owner_account_id uuid NULL, account_id uuid NULL,
 name varchar(140) NOT NULL, company varchar(180), email varchar(254), phone varchar(40), role varchar(100), segment varchar(100), company_size varchar(40),
 interest varchar(80) NOT NULL, desired_plan varchar(80), message varchar(1200), source varchar(120) NOT NULL DEFAULT 'Direct/Unknown', channel varchar(80) NOT NULL DEFAULT 'Direct/Unknown',
 utm_source varchar(200), utm_medium varchar(200), utm_campaign varchar(200), utm_term varchar(200), utm_content varchar(200), referral_code varchar(100), gclid varchar(300), fbclid varchar(300),
 landing_page varchar(500), referrer varchar(500), first_page varchar(500), last_page varchar(500), consent_at timestamptz, status varchar(40) NOT NULL DEFAULT 'New', assigned_user_id uuid,
 converted_account_id uuid, loss_reason_id uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false,
 CONSTRAINT ck_growth_leads_scope CHECK (tenant_owner_account_id IS NOT NULL OR account_id IS NOT NULL),
 CONSTRAINT ck_growth_leads_contact CHECK (email IS NOT NULL OR phone IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_growth_leads_scope_email_active ON orcafacil.growth_leads(COALESCE(tenant_owner_account_id, account_id), lower(email)) WHERE email IS NOT NULL AND is_deleted=false;
CREATE INDEX IF NOT EXISTS ix_growth_leads_pipeline ON orcafacil.growth_leads(status, created_at DESC) WHERE is_deleted=false;

CREATE TABLE IF NOT EXISTS orcafacil.growth_lead_events (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), event_type varchar(60) NOT NULL, from_stage varchar(40), to_stage varchar(40), reason varchar(500), metadata_json jsonb NOT NULL DEFAULT '{}', actor_user_id uuid, occurred_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE INDEX IF NOT EXISTS ix_growth_lead_events_lead ON orcafacil.growth_lead_events(lead_id, occurred_at DESC);
CREATE TABLE IF NOT EXISTS orcafacil.growth_lead_sources (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, code varchar(100) NOT NULL, name varchar(160) NOT NULL, channel varchar(80) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_owner_account_id, code));
CREATE TABLE IF NOT EXISTS orcafacil.growth_lead_scores (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), score integer NOT NULL CHECK(score BETWEEN 0 AND 100), classification varchar(30) NOT NULL, explanation_json jsonb NOT NULL, next_action varchar(300) NOT NULL, calculated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_lead_assignments (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), assigned_user_id uuid NOT NULL, assigned_by_user_id uuid, assigned_at timestamptz NOT NULL DEFAULT now(), ended_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS ux_growth_active_assignment ON orcafacil.growth_lead_assignments(lead_id) WHERE ended_at IS NULL;

CREATE TABLE IF NOT EXISTS orcafacil.growth_campaigns (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, name varchar(180) NOT NULL, campaign_type varchar(50) NOT NULL, channel varchar(30) NOT NULL, status varchar(30) NOT NULL DEFAULT 'Draft', preview_content text NOT NULL, confirmed_by_user_id uuid, confirmed_at timestamptz, starts_at timestamptz, ends_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK(status <> 'Running' OR confirmed_at IS NOT NULL));
CREATE TABLE IF NOT EXISTS orcafacil.growth_campaign_events (id uuid PRIMARY KEY, campaign_id uuid NOT NULL REFERENCES orcafacil.growth_campaigns(id), lead_id uuid REFERENCES orcafacil.growth_leads(id), event_type varchar(60) NOT NULL, detail varchar(1000), occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_utm_events (id uuid PRIMARY KEY, lead_id uuid REFERENCES orcafacil.growth_leads(id), anonymous_session_hash varchar(128), source varchar(200) NOT NULL DEFAULT 'Direct/Unknown', medium varchar(200), campaign varchar(200), term varchar(200), content varchar(200), referral_code varchar(100), gclid varchar(300), fbclid varchar(300), landing_page varchar(500), referrer varchar(500), occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_public_form_submissions (id uuid PRIMARY KEY, lead_id uuid REFERENCES orcafacil.growth_leads(id), form_type varchar(50) NOT NULL, request_fingerprint_hash varchar(128) NOT NULL, honeypot_triggered boolean NOT NULL DEFAULT false, submitted_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_growth_form_rate ON orcafacil.growth_public_form_submissions(request_fingerprint_hash, submitted_at DESC);
CREATE TABLE IF NOT EXISTS orcafacil.growth_contact_requests (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), request_type varchar(50) NOT NULL, status varchar(30) NOT NULL DEFAULT 'Requested', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_demo_requests (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), desired_at timestamptz, channel varchar(40) NOT NULL, assigned_user_id uuid, status varchar(30) NOT NULL DEFAULT 'Requested', notes varchar(2000), meeting_url varchar(1000), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_demo_schedules (id uuid PRIMARY KEY, demo_request_id uuid NOT NULL REFERENCES orcafacil.growth_demo_requests(id), scheduled_at timestamptz NOT NULL, meeting_url varchar(1000), scheduled_by_user_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_sales_opportunities (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), tenant_owner_account_id uuid NOT NULL, stage varchar(40) NOT NULL, assigned_user_id uuid, expected_monthly_value numeric(14,2), loss_reason_id uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz);
CREATE TABLE IF NOT EXISTS orcafacil.growth_sales_opportunity_events (id uuid PRIMARY KEY, opportunity_id uuid NOT NULL REFERENCES orcafacil.growth_sales_opportunities(id), event_type varchar(60) NOT NULL, detail varchar(1000), actor_user_id uuid, occurred_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.growth_sales_activities (id uuid PRIMARY KEY, opportunity_id uuid REFERENCES orcafacil.growth_sales_opportunities(id), lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), activity_type varchar(50) NOT NULL, due_at timestamptz, completed_at timestamptz, assigned_user_id uuid, notes varchar(2000), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_loss_reasons (id uuid PRIMARY KEY, tenant_owner_account_id uuid, code varchar(80) NOT NULL, name varchar(160) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS ux_growth_loss_reason ON orcafacil.growth_loss_reasons(COALESCE(tenant_owner_account_id, '00000000-0000-0000-0000-000000000000'::uuid), code);
CREATE TABLE IF NOT EXISTS orcafacil.growth_conversion_events (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), account_id uuid NOT NULL, plan_id uuid NOT NULL, conversion_type varchar(30) NOT NULL, source varchar(120) NOT NULL, channel varchar(80) NOT NULL, referral_code varchar(100), converted_by_user_id uuid NOT NULL, converted_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS ux_growth_conversion_real ON orcafacil.growth_conversion_events(lead_id, account_id, conversion_type);
CREATE TABLE IF NOT EXISTS orcafacil.growth_trial_funnels (id uuid PRIMARY KEY, lead_id uuid NOT NULL REFERENCES orcafacil.growth_leads(id), account_id uuid NOT NULL, trial_subscription_id uuid NOT NULL, status varchar(40) NOT NULL, started_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, loss_reason_id uuid, converted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(lead_id, account_id));
CREATE TABLE IF NOT EXISTS orcafacil.growth_pricing_intents (id uuid PRIMARY KEY, lead_id uuid REFERENCES orcafacil.growth_leads(id), plan_id uuid NOT NULL, billing_cycle varchar(20), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS orcafacil.growth_coupon_codes (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, code varchar(80) NOT NULL, name varchar(160) NOT NULL, description varchar(1000), discount_type varchar(40) NOT NULL, discount_value numeric(14,2) NOT NULL CHECK(discount_value >= 0), eligible_plan_id uuid, eligible_addon_id uuid, valid_from timestamptz NOT NULL, valid_until timestamptz NOT NULL, total_use_limit integer CHECK(total_use_limit IS NULL OR total_use_limit > 0), per_customer_limit integer NOT NULL DEFAULT 1 CHECK(per_customer_limit > 0), requires_approval boolean NOT NULL DEFAULT false, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), CHECK(valid_until > valid_from), UNIQUE(tenant_owner_account_id, code));
CREATE TABLE IF NOT EXISTS orcafacil.growth_coupon_redemptions (id uuid PRIMARY KEY, coupon_id uuid NOT NULL REFERENCES orcafacil.growth_coupon_codes(id), account_id uuid NOT NULL, email_normalized varchar(254), invoice_id uuid, original_amount numeric(14,2) NOT NULL CHECK(original_amount >= 0), discount_amount numeric(14,2) NOT NULL CHECK(discount_amount >= 0 AND discount_amount <= original_amount), approved_by_user_id uuid, redeemed_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_growth_coupon_uses ON orcafacil.growth_coupon_redemptions(coupon_id, account_id);
CREATE TABLE IF NOT EXISTS orcafacil.growth_referral_codes (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, owner_type varchar(30) NOT NULL, owner_id uuid NOT NULL, code varchar(80) NOT NULL, active boolean NOT NULL DEFAULT true, valid_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_owner_account_id, code));
CREATE TABLE IF NOT EXISTS orcafacil.growth_referral_events (id uuid PRIMARY KEY, referral_code_id uuid NOT NULL REFERENCES orcafacil.growth_referral_codes(id), lead_id uuid REFERENCES orcafacil.growth_leads(id), account_id uuid, conversion_event_id uuid REFERENCES orcafacil.growth_conversion_events(id), event_type varchar(40) NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_partner_programs (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, name varchar(160) NOT NULL, active boolean NOT NULL DEFAULT true, commission_percent numeric(5,2) NOT NULL CHECK(commission_percent BETWEEN 0 AND 100), commission_months integer NOT NULL CHECK(commission_months > 0), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orcafacil.growth_reseller_profiles (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, program_id uuid REFERENCES orcafacil.growth_partner_programs(id), name varchar(160) NOT NULL, company varchar(180), document varchar(40), email varchar(254) NOT NULL, phone varchar(40), status varchar(30) NOT NULL DEFAULT 'Prospect', level varchar(30) NOT NULL DEFAULT 'Bronze', assigned_user_id uuid, referral_code_id uuid REFERENCES orcafacil.growth_referral_codes(id), default_commission_percent numeric(5,2) NOT NULL CHECK(default_commission_percent BETWEEN 0 AND 100), notes varchar(2000), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz);
CREATE TABLE IF NOT EXISTS orcafacil.growth_reseller_accounts (id uuid PRIMARY KEY, reseller_id uuid NOT NULL REFERENCES orcafacil.growth_reseller_profiles(id), account_id uuid NOT NULL, conversion_event_id uuid NOT NULL REFERENCES orcafacil.growth_conversion_events(id), linked_at timestamptz NOT NULL DEFAULT now(), UNIQUE(reseller_id, account_id));
CREATE TABLE IF NOT EXISTS orcafacil.growth_reseller_commissions (id uuid PRIMARY KEY, reseller_id uuid NOT NULL REFERENCES orcafacil.growth_reseller_profiles(id), account_id uuid NOT NULL, billing_payment_id uuid NOT NULL, percentage numeric(5,2) NOT NULL CHECK(percentage BETWEEN 0 AND 100), paid_amount numeric(14,2) NOT NULL CHECK(paid_amount > 0), commission_amount numeric(14,2) NOT NULL CHECK(commission_amount >= 0), status varchar(30) NOT NULL DEFAULT 'Calculated', approved_by_user_id uuid, approved_at timestamptz, paid_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(reseller_id, billing_payment_id));
CREATE TABLE IF NOT EXISTS orcafacil.growth_reseller_payout_requests (id uuid PRIMARY KEY, reseller_id uuid NOT NULL REFERENCES orcafacil.growth_reseller_profiles(id), amount numeric(14,2) NOT NULL CHECK(amount > 0), status varchar(30) NOT NULL DEFAULT 'Pending', requested_at timestamptz NOT NULL DEFAULT now(), reviewed_by_user_id uuid, reviewed_at timestamptz);

CREATE TABLE IF NOT EXISTS orcafacil.growth_revenue_attribution (id uuid PRIMARY KEY, account_id uuid NOT NULL, billing_payment_id uuid NOT NULL, conversion_event_id uuid REFERENCES orcafacil.growth_conversion_events(id), source varchar(120) NOT NULL, channel varchar(80) NOT NULL, campaign_id uuid REFERENCES orcafacil.growth_campaigns(id), reseller_id uuid REFERENCES orcafacil.growth_reseller_profiles(id), amount numeric(14,2) NOT NULL CHECK(amount > 0), recognized_at timestamptz NOT NULL, UNIQUE(billing_payment_id));
CREATE TABLE IF NOT EXISTS orcafacil.growth_mrr_snapshots (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, snapshot_date date NOT NULL, current_mrr numeric(14,2) NOT NULL, new_mrr numeric(14,2) NOT NULL, expansion_mrr numeric(14,2) NOT NULL, contraction_mrr numeric(14,2) NOT NULL, churn_mrr numeric(14,2) NOT NULL, source_description varchar(300) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_owner_account_id, snapshot_date));
CREATE TABLE IF NOT EXISTS orcafacil.growth_channel_snapshots (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, snapshot_date date NOT NULL, channel varchar(80) NOT NULL, leads integer NOT NULL, conversions integer NOT NULL, paid_revenue numeric(14,2) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_owner_account_id, snapshot_date, channel));
CREATE TABLE IF NOT EXISTS orcafacil.growth_landing_page_variants (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, page_key varchar(120) NOT NULL, variant_key varchar(80) NOT NULL, active boolean NOT NULL DEFAULT false, content_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_owner_account_id, page_key, variant_key));
CREATE TABLE IF NOT EXISTS orcafacil.growth_commercial_notes (id uuid PRIMARY KEY, tenant_owner_account_id uuid NOT NULL, lead_id uuid REFERENCES orcafacil.growth_leads(id), opportunity_id uuid REFERENCES orcafacil.growth_sales_opportunities(id), author_user_id uuid NOT NULL, body varchar(4000) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(lead_id IS NOT NULL OR opportunity_id IS NOT NULL));
