using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace OrcaFacil.Persistence.Migrations;
public partial class AddAdvancedContractsV23 : Migration
{
 protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql(Sql);
 protected override void Down(MigrationBuilder migrationBuilder) { }
 private const string Sql = """
BEGIN;
CREATE TABLE IF NOT EXISTS orcafacil.contract_sla_policies (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, name varchar(120) NOT NULL, priority varchar(16) NOT NULL, response_time_minutes integer NOT NULL CHECK(response_time_minutes>0), resolution_time_minutes integer NOT NULL CHECK(resolution_time_minutes>0), business_hours_only boolean NOT NULL DEFAULT false, business_days_json jsonb NOT NULL DEFAULT '[1,2,3,4,5]', start_time time NOT NULL DEFAULT '08:00', end_time time NOT NULL DEFAULT '18:00', is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_sla_events (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, work_order_id uuid, support_ticket_id uuid, sla_policy_id uuid NOT NULL, event_type varchar(48) NOT NULL, occurred_at timestamptz NOT NULL, due_at timestamptz, idempotency_key varchar(180), details varchar(1000), created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.service_level_breaches (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, sla_policy_id uuid NOT NULL, work_order_id uuid, breach_type varchar(32) NOT NULL, due_at timestamptz NOT NULL, detected_at timestamptz NOT NULL, resolved_at timestamptz, idempotency_key varchar(180) NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_warranty_terms (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, client_id uuid NOT NULL, work_order_id uuid, service_catalog_item_id uuid, coverage varchar(500) NOT NULL, conditions varchar(2000), start_date date NOT NULL, end_date date NOT NULL CHECK(end_date>=start_date), status varchar(20) NOT NULL, cancellation_reason varchar(500), created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_preventive_schedules (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, client_id uuid NOT NULL, name varchar(160) NOT NULL, description varchar(2000) NOT NULL, frequency varchar(24) NOT NULL, interval integer NOT NULL CHECK(interval>0), start_date date NOT NULL, end_date date, next_run_date date NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_recurrence_runs (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, preventive_schedule_id uuid, run_type varchar(32) NOT NULL, period_start date NOT NULL, period_end date NOT NULL, idempotency_key varchar(200) NOT NULL, status varchar(24) NOT NULL, generated_entity_id uuid, error_summary varchar(500), created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_usage_allowances (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, usage_type varchar(40) NOT NULL, period_start date NOT NULL, period_end date NOT NULL, allowance_quantity numeric(18,4) NOT NULL CHECK(allowance_quantity>=0), used_quantity numeric(18,4) NOT NULL DEFAULT 0 CHECK(used_quantity>=0), unit varchar(30) NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_amendments (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, amendment_number varchar(40) NOT NULL, type varchar(40) NOT NULL, description varchar(2000) NOT NULL, effective_date date NOT NULL, previous_snapshot_json jsonb NOT NULL, new_snapshot_json jsonb NOT NULL, approved_by_user_id uuid, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_adjustments (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, adjustment_type varchar(32) NOT NULL, percent numeric(10,4), amount numeric(18,2), reason varchar(1000) NOT NULL, effective_date date NOT NULL, old_value numeric(18,2) NOT NULL, new_value numeric(18,2) NOT NULL CHECK(new_value>=0), status varchar(24) NOT NULL, created_by_user_id uuid NOT NULL, approved_by_user_id uuid, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_renewal_events (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, event_type varchar(32) NOT NULL, occurred_at timestamptz NOT NULL, approved_by_user_id uuid, reason varchar(1000), idempotency_key varchar(180) NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS orcafacil.contract_health_snapshots (id uuid PRIMARY KEY, account_id uuid NOT NULL, contract_id uuid NOT NULL, score integer NOT NULL CHECK(score BETWEEN 0 AND 100), classification varchar(30) NOT NULL, positive_factors_json jsonb NOT NULL, risk_factors_json jsonb NOT NULL, next_action varchar(500) NOT NULL, calculated_at timestamptz NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz, is_deleted boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS ux_contract_sla_event_key ON orcafacil.contract_sla_events(account_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_service_level_breach_key ON orcafacil.service_level_breaches(account_id,idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_contract_recurrence_key ON orcafacil.contract_recurrence_runs(account_id,idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_contract_renewal_key ON orcafacil.contract_renewal_events(account_id,idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_contract_usage_period ON orcafacil.contract_usage_allowances(account_id,contract_id,usage_type,period_start);
CREATE UNIQUE INDEX IF NOT EXISTS ux_contract_amendment_number ON orcafacil.contract_amendments(account_id,contract_id,amendment_number);
CREATE INDEX IF NOT EXISTS ix_contract_sla_active ON orcafacil.contract_sla_policies(account_id,contract_id,is_active);
CREATE INDEX IF NOT EXISTS ix_contract_warranty_expiry ON orcafacil.contract_warranty_terms(account_id,status,end_date);
CREATE INDEX IF NOT EXISTS ix_contract_preventive_due ON orcafacil.contract_preventive_schedules(account_id,is_active,next_run_date);
COMMIT;

""";
}
