namespace OrcaFacil.Web.Services;

public interface IContextualHelpService
{
    HelpContentDefinition? Find(string code);
    Task<HelpContentDefinition?> GetAsync(string code, CancellationToken cancellationToken = default);
    IReadOnlyList<HelpContentDefinition> ForPage(string page);
}

public sealed class ContextualHelpService : IContextualHelpService
{
    private static readonly HelpContentDefinition[] Content =
    [
        Help("dashboard", "Visão geral", "Priorize o trabalho comercial de hoje.", "Ao entrar no sistema.", "Tenha clientes e orçamentos cadastrados.", ["Confira os indicadores.", "Abra a lista de atenção.", "Execute a próxima ação sugerida."], "Um orçamento visualizado aparece como oportunidade de acompanhamento.", ["Indicadores zerados significam que ainda não há dados nesta conta."], "A atividade passa a compor o histórico.", "/Dashboard/Index"),
        Help("clients", "Clientes", "Centralize contatos e o histórico comercial.", "Antes de criar um orçamento ou consultar um relacionamento.", "Tenha nome e ao menos um meio de contato.", ["Busque ou filtre a lista.", "Abra um cliente para ver o histórico.", "Cadastre quando não encontrar."], "Busque por nome, telefone ou e-mail.", ["Confira se a conta correta está selecionada antes de cadastrar."], "O cliente fica disponível no orçamento.", "/Clients/Index"),
        Help("client.create", "Cadastro de cliente", "Guarde dados reutilizáveis com segurança.", "Quando um novo cliente solicitar uma proposta.", "Confirme se é pessoa física ou jurídica.", ["Preencha identificação.", "Informe contato e endereço.", "Revise e salve."], "Para empresa, use razão social e CNPJ válidos.", ["CEP indisponível não impede o preenchimento manual."], "Você pode criar o orçamento logo após salvar.", "/Clients/Create"),
        Help("services", "Catálogo de serviços", "Padronize descrições, unidades e preços.", "Quando um serviço é usado com frequência.", "Defina como ele é medido e seu preço padrão.", ["Pesquise o catálogo.", "Cadastre ou edite o serviço.", "Mantenha inativos os itens que não vende mais."], "Instalação elétrica · hora · R$ 120,00.", ["O preço padrão pode ser ajustado no orçamento."], "O item fica disponível no seletor do orçamento.", "/Services/Index"),
        Help("budget.client", "Orçamento: cliente", "Escolha para quem a proposta será preparada.", "Na primeira etapa do orçamento.", "Cadastre o cliente nesta mesma conta.", ["Pesquise o cliente.", "Confira contato e endereço.", "Avance para os serviços."], "Os dados atuais serão copiados para esta versão do orçamento.", ["Clientes de outra conta nunca são aceitos."], "O snapshot preserva os dados desta versão.", "/Documents/CreateBudget"),
        Help("budget.items", "Orçamento: serviços", "Monte o escopo e calcule valores.", "Depois de selecionar o cliente.", "Tenha ao menos um serviço ou item manual.", ["Adicione itens.", "Informe quantidade, preço e desconto.", "Confira o total calculado pelo servidor."], "2 horas × R$ 120,00 = R$ 240,00.", ["Totais digitados no navegador não são considerados."], "As condições usam o total recalculado.", "/Documents/CreateBudget"),
        Help("budget.conditions", "Orçamento: condições", "Explique validade, prazo e pagamento.", "Quando o escopo já estiver definido.", "Alinhe as condições comerciais aplicáveis.", ["Defina a validade.", "Informe prazo e pagamento.", "Adicione somente condições relevantes."], "Validade de 15 dias e 30% de sinal.", ["Não preencha parcelas ou garantia quando não se aplicarem."], "As condições aparecem na proposta e no PDF.", "/Documents/CreateBudget"),
        Help("budget.presentation", "Orçamento: apresentação", "Escolha a aparência da proposta.", "Antes da revisão final.", "Confira os recursos disponíveis no plano atual.", ["Compare as miniaturas.", "Visualize o modelo.", "Selecione a apresentação."], "Essencial privilegia objetividade; Profissional destaca a marca.", ["Um modelo bloqueado não altera o rascunho."], "A escolha integra o snapshot da revisão.", "/Documents/CreateBudget"),
        Help("budget.review", "Orçamento: revisão", "Valide a proposta antes de finalizá-la.", "Depois de completar todas as etapas.", "Confira cliente, itens, valores e condições.", ["Revise os avisos.", "Abra a prévia se necessário.", "Finalize quando estiver correto."], "Finalizar muda Rascunho para Pronto, sem enviar.", ["Volte à etapa correspondente para corrigir dados."], "Depois você poderá criar o link público.", "/Documents/CreateBudget"),
        Help("documents", "Orçamentos", "Acompanhe propostas do rascunho à aprovação.", "Para localizar, revisar ou compartilhar uma proposta.", "Selecione a conta correta.", ["Use busca e filtros.", "Abra os detalhes.", "Execute apenas a próxima ação disponível."], "Filtre por Visualizado para planejar retornos.", ["Uma proposta finalizada precisa de nova revisão para mudar."], "Cada ação entra na timeline comercial.", "/Documents/Index"),
        Help("document.details", "Detalhes do orçamento", "Consulte versão, valores, acesso público e decisão.", "Durante o acompanhamento comercial.", "Finalize o rascunho antes de compartilhar.", ["Confira a versão atual.", "Crie ou revogue o link.", "Acompanhe visualizações e decisão."], "Após aprovação, converta a proposta em ordem.", ["Nunca compartilhe um link revogado ou expirado."], "A próxima ação é calculada pelo estado.", "/Documents/Details"),
        Help("templates", "Modelos", "Reaproveite uma apresentação consistente.", "Quando quiser padronizar propostas.", "Confirme a disponibilidade no plano.", ["Compare modelos.", "Abra os detalhes.", "Escolha no orçamento."], "Use identidade visual profissional para destacar sua marca.", ["Modelos pagos ficam preservados no retorno ao Grátis."], "O modelo escolhido compõe a revisão.", "/Templates/Index", "Profissional"),
        Help("pipeline", "Pipeline comercial", "Visualize oportunidades por estágio.", "Em revisões diárias de vendas.", "Mantenha propostas e decisões atualizadas.", ["Observe as colunas.", "Identifique itens sem atividade.", "Abra a próxima ação."], "Visualizado sugere acompanhamento; Aprovado permite criar ordem.", ["O estágio vem do backend e não muda por arrastar cartões."], "A timeline registra a evolução.", "/Documents/Pipeline"),
        Help("work-orders", "Ordens de serviço", "Execute o que foi aprovado.", "Depois da aprovação do orçamento.", "Converta a revisão aprovada em ordem.", ["Abra a ordem.", "Agende o responsável.", "Inicie e conclua na sequência."], "Uma ordem planejada oferece Agendar; uma agendada oferece Iniciar.", ["Ações incompatíveis com o estado ficam indisponíveis."], "Após concluir, registre o pagamento.", "/WorkOrders/Index"),
        Help("schedule", "Agenda", "Organize serviços por dia, semana ou lista.", "Para distribuir e acompanhar a execução.", "Agende a ordem e, se possível, atribua um responsável.", ["Escolha o período.", "Filtre responsável e status.", "Abra a próxima ação do cartão."], "Reagende antes do início quando o cliente mudar o horário.", ["Conflitos devem ser resolvidos antes de confirmar."], "Início e conclusão atualizam a ordem.", "/Schedule/Index"),
        Help("payment", "Registrar pagamento", "Informe um recebimento ligado à ordem.", "Após a execução ou conforme a condição acordada.", "Confira valor previsto, já registrado e saldo.", ["Informe valor, método e data.", "Adicione uma observação útil.", "Confirme o registro."], "Este registro é informado por você e não representa confirmação bancária automática.", ["Não registre novamente ao recarregar; a operação é idempotente."], "O recibo pode ser emitido após a confirmação.", "/Payments/Register"),
        Help("receipt", "Recibo", "Comprove o pagamento informado na operação.", "Depois de registrar o pagamento.", "Revise emitente, cliente, valor e serviço.", ["Confira a prévia.", "Gere ou baixe o PDF.", "Compartilhe com o cliente."], "O valor também aparece por extenso.", ["O recibo não substitui documento fiscal quando exigido."], "O evento aparece no histórico do cliente e da ordem.", "/Receipts/Details"),
        Help("my-plan", "Meu plano", "Entenda benefícios, uso, limites e regularização.", "Antes de usar um recurso ou ao receber um aviso de limite.", "Confira o plano escolhido e o disponível agora.", ["Veja os usos.", "Compare planos.", "Regularize benefícios pausados quando necessário."], "No fallback Grátis, seus dados continuam preservados.", ["Plano escolhido e plano efetivo podem ser diferentes durante suspensão."], "A regularização restaura benefícios automaticamente.", "/Subscription/Index"),
        Help("admin.dashboard", "Central operacional", "Monitore contas, receita, filas, erros e saúde.", "Na rotina do SuperAdministrador.", "Use uma conta com autorização de plataforma.", ["Revise alertas prioritários.", "Abra a conta afetada.", "Audite a ação tomada."], "Uma outbox acumulada exige verificar SMTP e worker.", ["Não trate readiness estático como evidência de saúde."], "A Conta 360 reúne a investigação.", "/Admin/Index"),
        Help("admin.account360", "Conta 360", "Investigue plano, uso, financeiro e operação em um só lugar.", "Ao atender ou auditar uma conta.", "Localize a conta pela busca administrativa.", ["Escolha a aba.", "Consulte dados paginados.", "Execute ações autorizadas e registre o motivo."], "Compare plano escolhido, efetivo, consumo e pagamentos.", ["PII permanece mascarada sem permissão de revelação."], "Toda ação sensível produz auditoria.", "/Admin/Accounts/Details"),
        Help("admin.payments", "Pagamentos da plataforma", "Acompanhe cobranças e eventos financeiros.", "Ao conciliar ou investigar uma suspensão.", "Tenha identificador da conta ou pagamento.", ["Filtre o período e status.", "Abra o pagamento.", "Compare eventos e assinatura."], "Pagamento pendente pode manter carência antes do fallback.", ["Não confunda pagamento manual de ordem com cobrança do plano."], "Uma correção atualiza a experiência de plano.", "/Admin/Payments/Index"),
        Help("admin.health", "Saúde da plataforma", "Verifique dependências reais da operação.", "Diante de readiness degradado, filas ou erros.", "Tenha acesso operacional autorizado.", ["Confira banco, schema e migrations.", "Valide SMTP, outbox e workers.", "Correlacione erros antes de agir."], "Banco saudável com worker parado ainda degrada envios.", ["Nunca exponha segredos ou PII em diagnósticos."], "Registre a investigação e acompanhe a recuperação.", "/Admin/Health/Index")
    ];

    public HelpContentDefinition? Find(string code) => Content.FirstOrDefault(x => x.Code.Equals(code, StringComparison.OrdinalIgnoreCase));
    public Task<HelpContentDefinition?> GetAsync(string code, CancellationToken cancellationToken = default) => Task.FromResult(Find(code));
    public IReadOnlyList<HelpContentDefinition> ForPage(string page) => Content.Where(x => x.RelatedPage.Equals(page, StringComparison.OrdinalIgnoreCase)).ToArray();

    private static HelpContentDefinition Help(string code, string title, string purpose, string whenToUse, string beforeStarting,
        IReadOnlyList<string> steps, string example, IReadOnlyList<string> commonErrors, string whatHappensNext, string relatedPage, string? requiredPlan = null) =>
        new(code, title, purpose, purpose, example, "help", relatedPage, requiredPlan, HelpDisplayMode.Drawer, 10, 1,
            whenToUse, beforeStarting, steps, commonErrors, whatHappensNext, relatedPage);
}

public sealed record HelpContentDefinition(string Code, string Title, string Summary, string Explanation, string Example, string Icon,
    string RelatedPage, string? RequiredPlanCode, HelpDisplayMode DisplayMode, int DisplayOrder, int Version,
    string WhenToUse, string BeforeStarting, IReadOnlyList<string> Steps, IReadOnlyList<string> CommonErrors,
    string WhatHappensNext, string RelatedAction);
public enum HelpDisplayMode { Tooltip, Popover, Drawer, Modal }
